cyberark/secretless-broker

Jenkinsfile

Since we are still doing heavy development on the website, let's update the Jenkinsfile to publish the `master` branch to the staging site again for now.

Update Jenkinsfile to publish master to staging site

---

.goreleaser.yml
bin/Dockerfile.releaser
bin/build_release

With this setup, we are now able to build binary archives to add to
GitHub when we tag a release, replacing many manual steps we did before.
We still have to trigger/upload manually when we tag but that will be
tackled in a separate task.
Resolves #305 
Note: Jenkins build results do not apply since this code path is run manually

Added Goreleaser for automated binary archive building (for tags)

---

internal/app/secretless/handlers/http/aws.go
internal/app/secretless/handlers/http/basic_auth.go
internal/app/secretless/handlers/http/conjur.go
internal/app/secretless/handlers/mysql/backend.go
internal/app/secretless/handlers/mysql/handler.go
internal/app/secretless/handlers/pg/backend.go
internal/app/secretless/handlers/pg/handler.go
internal/app/secretless/handlers/ssh/handler.go
internal/app/secretless/handlers/sshagent/handler.go
internal/app/secretless/listeners/http/listener.go
internal/app/secretless/listeners/mysql/listener.go
internal/app/secretless/listeners/pg/listener.go
internal/app/secretless/listeners/ssh/listener.go
internal/app/secretless/listeners/sshagent/listener.go
internal/app/secretless/proxy.go
internal/pkg/plugin/manager.go
pkg/secretless/plugin/v1/handler.go
pkg/secretless/plugin/v1/listener.go
test/plugin/example/backend.go
test/plugin/example/handler.go
test/plugin/example/listener.go

+ ensures connections are closed in the event of an error in Piping
+ when Secretless receives an interrupt, or otherwise, there is a graceful shutdown path for Proxy -> Listeners -> Handlers
+ refactor: use channel to communicate Proxy#Run loop actions; remove run loop waitgroup
+ introduces HandlerShutdownNotifier to HandlerOptions (to inform listeners of dead handlers)
+ to avoid the copy and paste hell when introducing Handler#Shutdown interface method, I went ahead and did some clean up
+ refactor: remove redundancy by introducing BaseHandler and BaseListener. i.e. reusability through embedded structs :rocket:
Closes #47 
Don't just copy. Run step by step and read between the lines.
```
docker network create dev-net
docker run --net dev-net \
--rm \
-it \
--name dev-postgres \ …
```

feat: handlers informs clients of close connections and secretless shutdown 

---

test/pg_handler/pg_test.go

I have no idea how tests have been passing prior to this.

fix: pg_test.go TCP requires sslmode=disable

---

internal/app/secretless/handlers/mysql/handler.go
internal/app/secretless/handlers/pg/handler.go
internal/app/secretless/listeners/mysql/listener.go
internal/app/secretless/listeners/pg/listener.go
internal/app/secretless/listeners/ssh/listener.go
internal/app/secretless/listeners/sshagent/listener.go
pkg/secretless/plugin/v1/listener.go

Old code would keep old listener gofuncs running after listeners were
closed which would keep erroring out on `Accept`s and keep the loops
spinning forever, driving the CPU usage up to 100%. We now flag the
listerner as being wound down and check that flag in the accept loops,
allowing us to exit listener once the shutdown has begun.
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/fix-broken-shutdown/)

Fixed soft-reload 100% CPU bug

---

cmd/secretless-broker/main.go
go.mod
go.sum
internal/pkg/plugin/fs_watcher.go
internal/pkg/plugin/manager.go

We want to be able to support dynamic changes to the configuration files
so this code change allows us to do so by using notifications which
trigger a reload.
Resolves #211 
[Jenkins Build](https://jenkins.conjur.net/view/conjurinc/job/conjurinc--secretless/job/211-config-file-watch/)
How to test:
- Launch secretless with `-watch` flag
- Make changes to the config file
- Verify that the configuration got updated

Added ability for Secretless to watch for configuration file changes

---

bin/abspath
bin/build
bin/build_release
bin/build_website
bin/check_website_links
bin/publish_website
bin/test_quickstart
bin/test_unit

We don't want to depend on something that's not in a base install of OSX
for basic building (other than Docker) so we now use pure Bash to
assemble paths that Docker is fine with mounting.
Resolves #329 
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/329-fix-realpaths/)

Removed the need for realpath (coreutils)

---

internal/app/secretless/providers/kubernetes-secrets/provider.go

In the old code a secret ID like "meow" will panic with an "out of bounds" error when this code is run:
```
tokens := strings.SplitN(id, "#", 2)
secretName, fieldName := tokens[0], tokens[1]
```

fix: avoid out of bounds panic by validating kubernetes secret id

---

demos/full-demo/src/ansible/Dockerfile
demos/full-demo/src/myapp/Dockerfile
demos/quick-start/docker/Dockerfile

This PR addresses:
+ An error while executing `docker-compose build` under `secretless-broker/demos/full-demo` for both `plaintext` and `conjur`:
```
Error: `Step 7/8 : RUN go mod -sync
---> Running in 4a44651d6b9c
go: modules disabled inside GOPATH/src by GO111MODULE=auto; see ‘go help modules’
ERROR: Service ‘myapp’ failed to build: The command ‘/bin/sh -c go mod -sync’ returned a non-zero code: 1` 
```
+ Updates the demos to use the DockerHub Secretless image

 fix: avoid failing build -> set GO111MODULE=on for full-demo/myapp

---

docs/_sass/_media.scss

closes #347 
Regardless of mobile screen size, this ensures that card features boxes are even in height
Max-width 1200px
Before:
After:
Max-width 990px
Before:
After:

Add styling to ensure card features are same size

---

internal/app/secretless/handlers/http/conjur.go
internal/app/secretless/providers/conjur/provider.go
internal/app/secretless/providers/env/provider.go
internal/app/secretless/providers/file/provider.go
internal/app/secretless/providers/keychain/provider.go
internal/app/secretless/providers/kubernetes-secrets/provider.go
internal/app/secretless/providers/literal/provider.go
internal/app/secretless/providers/providers.go
internal/app/secretless/providers/vault/provider.go
internal/app/summon/command/command.go
internal/pkg/plugin/manager.go
internal/pkg/plugin/resolver.go
test/conjur/conjur_provider_test.go
test/plugin/example/cmd/main.go
test/plugin/example/provider.go
test/vault_provider/vault_provider_test.go

Resolves #340
This change cleans up handler implementations (mostly changing receiver types) and instantiates a Conjur provider from the Conjur handler.

Conjur handler consumes access token from Conjur provider

---

docs/_includes/cta-banner-integ.html
docs/_includes/cta-banner.html
docs/_includes/side_navigation.html
docs/_layouts/docs.html
docs/_sass/_elements.scss
docs/_sass/_footer.scss
docs/docs/get_started/quick_start.md
docs/index.md

closes #338
This PR addresses the following:
- add K8 banner
- fixes dropped active class from side navbar
K8 Banner
Before
After
Active Class
Before
After

Add k8 banner and fix dropped active class

---

pkg/secretless/plugin/v1/listener_test.go

Closes #173.
**Issue was previously fixed.** Likely fixed along with #290 (see [UnixConn.File](https://golang.org/pkg/net/#UnixConn.File) for more info).
This PR adds a test to ensure that the BaseListener shuts down without error and
cleans up any socket files that were in use.

Add test for clean listener shutdown

---

.dockerignore
Jenkinsfile
bin/check_style
internal/app/secretless/providers/kubernetessecrets/client.go
internal/app/secretless/providers/kubernetessecrets/provider.go
internal/app/secretless/providers/providers.go
test/plugin/example/conn_manager.go

Resolves #367 
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/fix-linting/)
Linting is currently broken (doesn't trigger failures) so this change
ensures that the errors are enforced as expected.

Fix linting error handling

---

cmd/secretless-broker/main.go
internal/app/secretless/configurationmanagers/configfile/fs_watcher.go
internal/app/secretless/configurationmanagers/configfile/manager.go
internal/app/secretless/configurationmanagers/configuration_managers.go
internal/app/secretless/proxy.go
internal/pkg/plugin/manager.go
test/http_basic_auth/docker-compose.yml
test/plugin/example/conn_manager.go

Resolves #366 
Resolves #102 
Resolves #74 
Resolves #215 
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/366-configfile-config-manage/)
Since we now can use configuration manager plugins, we now have our
regular config file reading moved into this abstraction. The CLI
interactions have not been changed so it is a fully backward-compatible
feature.
How to test:
- Run the CLI with any of the default switches `-f <config>`, `-watch`, and then try without and to see the traversal logic.

Made configuration file reading use a configuration manager plugin

---

Dockerfile
internal/app/secretless/providers/conjur/provider.go

The Conjur provider with the Kubernetes authenticator requires a couple of directories be available for the Conjur certificate and the access token. This PR updates the Secretless image to ensure these directories will be available and owned by the `secretless` user.
The Conjur provider is updated to provide appropriate resource IDs to the Conjur Go API.

Updates to Secretless to get Conjur K8s authenticator working

---

internal/app/secretless/configurationmanagers/kubernetes/crd/crd_injector.go

Fixes #389 
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/389-crd-capitalization/)
Without this, we don't have a matching 'kind' between our examples
configuration, our standalone injector, and the integrated injector.

Make the integrated CRD injector use capitalized names for 'Kind' field

---

.goreleaser.yml
bin/Dockerfile.releaser

Since mercurial is needed to fetch the broker dependencies, we need it
in the releaser container too.

Add Mercurial to releaser dependencies

---

.goreleaser.yml
bin/Dockerfile.releaser

Resolves #396
We can now target distributions with packages rather than just providing
a single binary.

Added ability to build deb/rpm packages

---

docs/_layouts/landing.html
docs/docs/overview/why_secretless.md

Resolves #422 
Updates "Why Secretless?" page to be more consistent with other language currently being used on the site. This includes the arguments for using Secretless to improve responsiveness to rotation; there is future work to be done to really nail the rotation story, so it's best to remove this content until that later date.
Also makes a minor change to the "Use Open Source" feature on the main page.

"Why secretless?" page is updated for consistency

---

docs/docs/reference/handlers/overview.md
docs/docs/reference/providers/overview.md

Instead of pointing just to the GH issues page, point to the page that shows epics for Secretless Handlers.
This will more accurately show the handlers currently in dev.

Update link to GH issues for handlers in dev

---

test/pg_handler/bench_test.go
test/pg_handler/docker-compose.yml
test/pg_handler/pg_test.go
test/pg_handler/secretless.yml

Closes #364 
Benchmarking runs a series of SELECT queries directly to Postgres and
through Secretless over TCP.
Running the benchmark:
```
→ cd test/pg_handler
→ ./start
[...]
→ PG_ADDRESS=localhost:5432
→ SECRETLESS_ADDRESS=localhost:15432
→ go test -v -bench=. -test.benchtime=10s ./bench_test.go
go: finding github.com/cyberark/conjur-api-go v0.5.0
goos: linux
goarch: amd64
BenchmarkBaseline_Select1-4               100000            153786 ns/op
BenchmarkBaseline_Select10-4              100000            169145 ns/op
BenchmarkBaseline_Select100-4             100000            176324 ns/op
BenchmarkBaseline_Select1000-4             50000            274557 ns/op
BenchmarkBaseline_Select10000-4            50000            407285 ns/op
BenchmarkSecretless_Select1-4              50000 …
```

Add Postgres benchmarking

---

internal/app/secretless/handlers/mysql/protocol/protocol_test.go

Relocate the MySQL protocol unit tests to the directory where the protocol lives, as is standard practice with Go code.
With this change, the MySQL protocol tests will run with the rest of the unit tests when `./bin/test_unit` is called.

Moving MySQL protocol unit tests

---

.gitignore
Jenkinsfile
bin/test_benchmarks
test/http_basic_auth/test
test/mysql_handler/test
test/pg_handler/Dockerfile.dev
test/pg_handler/bench_test.go
test/pg_handler/docker-compose.yml
test/pg_handler/secretless.yml
test/pg_handler/start
test/pg_handler/test
test/pg_handler/test.sql
test/plugin/test
test/ssh_agent_handler/test
test/ssh_handler/test

Resolves #364 
Updates the pg benchmark to return more consistent results
- Adds a volume to the pg instance to avoid using overlayfs for io ops that aren't in ram
- References pg / secretless by container IP instead of name so that DNS lookup will not impact performance
Adds benchmark tests to the CI pipeline
- Parallelizes the test suite runs
- Adds benchmark tests (if the test directory has a bench_test.go file included)
TODO:
- red build if benchmark run fails (logged issue #471)

Run pg benchmarks with test suite

---

docs/_data/navigation.yml

Update to add a link to FAQ to the dropdiwn for Docs in the top nav. 
**To test:**
1. Check that FAQ link is appearing in the nav in the Docs dropdown 
2. Confirm that when navigating to the FAQ page, the Docs top nav item, and FAQ item within the dropdown are using the blue active link style (shown below)

Link to FAQ is added to Docs dropdown in top nav

---

bin/test_benchmarks
docs/.gitignore

- Auto-generates line of code counts and docker image size
- Formats as HTML to facilitate loading into website

Add metrics to benchmarks

---

docs/_sass/_navbar.scss

**What does this PR do?**
Connected to #503 
Updates Staging to:
1. Removes :focus pseudo class causing a blue highlight when dropdown menus opened in Safari
2. Prevents caret for dropdown menus from disappearing when menu opened
**Before**
**After**

503 - Dropdown fixes

---

bin/build
bin/build_utils
bin/publish

* TODO: Pipeline stages really shouldn't rely on `secretless-*:latest`. We'll end up with race conditions on concurrent builds. A better alternative  is `secretless-*:$TAG`

fix(pipeline): add missing and fix broken tags

---

bin/test_integration

`./bin/test_integration` currently runs all the tests and has no mechanism for customisation.
The ability to specify individual test_folders and the local flag would improve developer experience.
Currently, the developer has to run the test steps manually.
~None. Small and spur of the moment.~
Connected to #530
`./bin/test_integration`
1. Run `./bin/test_integration` and ensure it runs as usual and covers all the tests. This is also confirmed by the green build.
2. Run `./bin/test_integration -x`, it should complain about an invalid option and provide help and exit with 1
3. Run `./bin/test_integration --help`, it should provide help and exit with 0
4. Add a dummy test to `kubernetes_provider`
5. Run `./bin/test_integration kubernetes_provider`, it should only run the previously baked …

refactor(pipeline): allow ./bin/test_integration to specify individual test_folders

---

docs/_includes/footer.html

Updates Google Group link text
#560 
• Run the website locally, and confirm that the link to the Google Group reads "Google Group" (screenshot below)
• Confirm that the link sends you to: https://groups.google.com/forum/#!forum/secretless
n/a
n/a

Update footer link for Google Group

---

CONTRIBUTING.md

Previously, the secretless contributing docs had 'notes' that were not uniform. Some were capitalized, bolded, or not given its own line. Our aim should keep the styling uniform across the Secretless GH docs. I made the styling uniformed with the README.md docs, italics.
Connected to #576 
CONTRIBUTING.MD
BEFORE:
AFTER:

Correct notes styling so that they match with the README

---

go.mod
go.sum

Use the latest commit bb43c2b86d76e1028e6784a59c4579703eeb9922 of conjur-api-go
to pick up the changes made to LoadConfig for envs that can't use user.Current (see cyberark/conjur-api-go#39)
Connected to #582

Update conjur-api-go dependency

---

docs/docs/reference/providers/conjur.md

Connected to #401 
It's a single documentation page change
N/A

add conjur provider k8s authenticator documentation

---

CHANGELOG.md
internal/app/secretless/handlers/http/aws.go
internal/app/secretless/handlers/mysql/backend.go
internal/app/secretless/handlers/pg/backend.go
internal/app/secretless/handlers/ssh/handler.go
internal/app/secretless/handlers/sshagent/handler.go
internal/app/secretless/listeners/http/listener.go

We still had a few handlers/listeners that were dumping information to
the CLI when debug was turned on so we now don't do that in any of them
hopefully.
Redacts pg/mysql/aws credentials from debug output
Connected to #593 
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/593-redact-backend-vars/)
https://github.com/cyberark/secretless-broker/issues/495

Made more handlers/listeners not dump credentials in debug mode

---

cmd/secretless-broker/main.go
demos/full-demo/conjur/docker-compose.yml
demos/k8s-demo/etc/secretless.yml
docs/docs/get_started/kubernetes_tutorial.md
docs/docs/reference/handlers/http/aws.md
test/aws_handler/secretless.yml
test/conjur/secretless.dev.yml
test/conjur/secretless.yml
test/http_basic_auth/secretless.yml
test/plugin/secretless.dev.yml
test/plugin/secretless.yml
test/ssh_agent_handler/secretless.dev.yml
test/ssh_agent_handler/secretless.yml
test/ssh_handler/secretless.yml

Also updates the secretless main.go to note that the debug flag is for
development purposes only. This caveat should remain in place until such time
as we are auto-reviewing logs to ensure no leakage of secret data even in debug
mode, and the debug values are actually set up to be helpful to an end user who
is trying to debug the broker (as opposed to being useful to a developer, who
has a deep knowledge of the product and is trying to understand its internals).
Connected to #584

Remove debug from all demos and examples

---

CHANGELOG.md
Dockerfile

Old setup would fail on OpenShift since UID would not match the random
UID that is forced in those environments so here we ensure that all
writable directories have write permission by GID 0.
Connected to https://github.com/conjurdemos/kubernetes-conjur-demo/issues/23
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/fix-oc-permissions/)

Made permissions fixes for OpenShift deployment

---

CONTRIBUTING.md
Dockerfile
Dockerfile.dev
Dockerfile.test

Also update the CONTRIBUTING documentation to ensure devs use a min Go version
of 1.11.4 and to remove the note about checksum conflicts in client-go.
Validated that running the manual keychain test did not lead to any conflicts in go.sum (prior to Go1.11.4, it would).
Connected to #603

Remove go.sum hacks from Dockerfiles

---

go.mod
go.sum
internal/app/secretless/handlers/mysql/backend.go
internal/app/secretless/handlers/mysql/handler.go
internal/app/secretless/handlers/mysql/protocol/error.go
internal/app/secretless/handlers/mysql/protocol/protocol.go
internal/app/secretless/handlers/mysql/protocol/protocol_test.go
pkg/secretless/plugin/v1/handler.go
test/mysql_handler/docker-compose.yml
test/mysql_handler/pkg/run_test_case.go
test/mysql_handler/start
test/mysql_handler/test
test/pg_handler/test

Connected to #613
Connected to #614
TODO: Add comments to `/internal/app/secretless/handlers/mysql/protocol/protocol_test.go` of how expected values were generated

fix/handler/mysql: handle authPluginName mismatch + consistent sequenceIds

---

bin/Dockerfile.website
bin/build_website

Previously we were trying to install go-tools to be able to run the godoc
command in the website Docker image, but this was broken when godoc was merged
into the main go binary. To address this, we no longer install go-tools in the
ruby image, but instead build the godocs using the same go image we use for
the project build.

Updating website build to gen godocs in go img

---

docs/_data/navigation.yml

Linking to "Why Secretless"
Fixes a broken link to _Why Secretless_ in the footer
Connected to #655
Run the site locally, and confirm that the _Why Secretless_ link in the footer links to:  https://docs.secretless.io/Latest/en/Content/Overview/overview.htm#WhySecretless
Have you run the following manual tests to verify existing functionality continues to function as expected? n/a
n/a
n/a

fixing broken link in footer

---

docs/_data/navigation.yml
docs/_sass/_defaults.scss
docs/docs/get_started/kubernetes_tutorial.md

Adds some light css styling to .note & .change-role callouts
Connected to https://github.com/cyberark/secretless-docs/issues/103
1. Run the site locally, and go to: /docs/get_started/kubernetes_tutorial.html
2. Check that **note** and **change-role** styling is updated
n/a
Have you run the following manual tests to verify existing functionality continues to function as expected? no
If this feature does not have any/sufficent automated tests, have you created/updated a folder in `test/manual` that includes: No. Only minimal style changes.
n/a
n/a

103 note styling

---

README.md
docs/_includes/quick_start.html

Resolves https://github.com/cyberark/secretless-broker/issues/375
Resolves https://github.com/cyberark/secretless-docs/issues/95

fix quick start docs so any psql CLI works

---

.gitlab-ci.yml
demos/quick-start/README.md
demos/quick-start/test/bin/entrypoint

+ update gitlab ci to use prebaked image
+ use universal psql command in quick-start README

update demos/quick-start/README.md to use universal psql command

---

README.md

We currently only support authenticating with HCV using `VAULT_ADDR` and `VAULT_TOKEN`, but this isn't the [recommended way](https://www.vaultproject.io/docs/auth/kubernetes.html) to auth with HCV in K8s. Until we add support for recommended auth mechanisms this provider is listed as `alpha`.

Mark HCV provider as alpha

---

bin/juxtaposer/formatter/util/util.go
bin/juxtaposer/formatter/util/util_test.go

add unit test for juxtaposer

---

bin/juxtaposer/README.md

This change updates the README of perf agent to be closer
to reality since we no longer have `Type` nor `Style` configuration
fields.
README
N/A

Updated README of perf agent to reflect new config changes

---

bin/juxtaposer/Dockerfile
bin/juxtaposer/README.md
bin/juxtaposer/config/config.go
bin/juxtaposer/deploy/juxtaposer_deployment_template.yml
bin/juxtaposer/deploy/juxtaposer_mysql.yml
bin/juxtaposer/deploy/juxtaposer_pg.yml
bin/juxtaposer/formatter/api/formatter.go
bin/juxtaposer/formatter/json/json.go
bin/juxtaposer/formatter/stdout/stdout.go
bin/juxtaposer/formatter/util/util.go
bin/juxtaposer/formatter/util/util_test.go
bin/juxtaposer/go.mod
bin/juxtaposer/go.sum
bin/juxtaposer/juxtaposer.yml
bin/juxtaposer/main.go
bin/juxtaposer/tester/api/db_tester.go
bin/juxtaposer/tester/api/driver_manager.go
bin/juxtaposer/tester/db/db.go
bin/juxtaposer/tester/db/sql/sql.go
bin/juxtaposer/timing/timing.go

This PR adds the following perf agent (juxtaposer) capabilities:
- Ability to test reopened connections
- Ability to test backends with user-set number of parallel threads
Additional features added/changed:
- Added ability to stream-process results asynchronously
- Added ability to stream-process test runs
- Cleaned up timing-related logic
- Made round-based limit be the minimum rounds for all backends (ensures proper comparison)
Connected to #739 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/734-additional-performance-tests/)
N/A - this _is_ the testing tool

734 Additional Performance Tests

---

bin/juxtaposer/README.md

Old example used a path that was not standard and needed
extra work to set up so now we ensure that we don't need
any of that by using `/tmp`

Moved perf agent example socket paths to `/tmp`

---

bin/juxtaposer/aggregate.py

This code takes the raw verbose output from Juxtaposer and produces the
results that we want to use for our metrics. Eventually this code will
be retired after Juxtaposer natively supports this type of output data.
N/A but
Connected to #759 

Added aggregation script to perf tester code

---

bin/publish

We don't want intermediate master tags to end up on Dockerhub so we now
push those to the internal registry.
Connected to #719 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/719-dont-push-all-master-commits/)
N/A
N/A
N/A

Changed pushing of intermediate tags to internal registry

---

go.mod
go.sum

This will change our root dependency from yaml.v1 to yaml.v3 which is
what will align the lic between our products as well as pull in any
improvements into the codebase.
Connected to #785 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/upgrade-summon/)

Upgrade summon module dependency to 0.7.0

---

.codeclimate.yml
CONTRIBUTING.md
bin/check_style

From the commit message:
- Change bin/check_style script to call codeclimate via Docker
- Remove check_style task from Jenkinsfile, since it will now be run by
Code Climate
- Turn on codeclimate golint engine and configure it to match the
directories we were testing with check_style
- Update CONTRIBUTING.md to document the new codeclimate use
I also created a test branch and PR to verify that Code Climate will in fact now fail on linting errors:
https://github.com/cyberark/secretless-broker/pull/783
This confirmed CC is failing linting errors as expected.
Not performed.

Replace check_style linting with codeclimate golint engine

---

bin/test_unit
test/pg_handler/start

Hotfix to address linux portability issue with `mkdir --parents` discovered by @sgnn7:
https://conjurhq.slack.com/archives/CBTETAE20/p1564418130172200

All relevant mkdir commands use portable -p instead  --parents

---

CONTRIBUTING.md
README.md
bin/juxtaposer/README.md
demos/quick-start/docker/Dockerfile
demos/quick-start/docker/etc/secretless.yml
design/simpler-configuration.md
design/tls-support-plan.md
docs/tutorials/kubernetes/sec-admin.md
internal/app/secretless/handlers/pg/backend.go
internal/app/secretless/handlers/pg/handler.go
internal/app/secretless/listeners/pg/listener.go
pkg/secretless/config/v2/config_test.go
test/util/testutil/config_generator.go
test/util/testutil/types.go

Changes PG connector configuration to match MySQL. Effectively, it changes `address` field into `host` and `port` fields.
Connected to https://github.com/cyberark/secretless-broker/issues/661
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/661-unify-pg-and-mysql-configs/)
- [N/A] Manually tested [Keychain provider](https://github.com/cyberark/secretless-broker/tree/master/test/manual/keychain_provider)
https://github.com/cyberark/secretless-docs/issues/181

661 unify pg and mysql configs

---

bin/prefill_changelog

We were missing an import and we needed to account for unbound variable
$1 when running. This commit should fix both issues.

Fix problems with prefil_changelog running

---

internal/app/secretless/handlers/mysql/connection_details.go
internal/app/secretless/handlers/mysql/connection_details_test.go
internal/app/secretless/handlers/mysql/handler.go

Since in most cases, we know that the MySQL port is 3306, it is
superfluous to need that in the config if the user is connecting to the
default port setting. This commit also reorganizes the code a bit for
better testability and adds a few tests around this feature.
Connected to https://github.com/cyberark/secretless-broker/issues/805
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/805-mysql-default-port-set/)

Made MySQL connector able to guess the 3306 port if it is not provided

---

internal/pkg/util/health_test.go

We're seeing occasional failures in this test, such as:
https://jenkins.conjur.net/job/cyberark--secretless-broker/job/master/351/testReport/(root)/util/Run_Tests___Unit_tests___Test_Health/
This is a quickfix to attempt to reduce or eliminate them.  We will
likely add a proper fix in the future per:
https://conjurhq.slack.com/archives/CBTETAE20/p1564774890366200?thread_ts=1564758060.354900&cid=CBTETAE20

Wait longer for server to come up in health check test

---

CHANGELOG.md
internal/app/secretless/handlers/pg/backend.go
internal/app/secretless/handlers/pg/backend_config.go
internal/app/secretless/handlers/pg/backend_config_test.go
internal/app/secretless/handlers/pg/handler.go
internal/app/secretless/listeners/pg/listener.go

Returns ability to define PG connector with an address
Connected to #807
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/807-add-back-pg-address-support/)

807 Add back pg address support

---

CHANGELOG.md
CONTRIBUTING.md
README.md
pkg/secretless/version.go

Other things done in this PR:
- Add note to README about pre-releases
- Update contributor release instructions to include marking a release as a
"pre-release" until the stable quality exercises have been completed

Bump version to 1.1.0

---

k8s-ci/utils.sh

The recent change made the gke-utils image be built with included
context, making the build process slower than it needed to be. This
change reverts this and moves the image building back to a no-context
build.

Reverted gke-utils image build to not use any context

---

internal/app/secretless/handlers/http/aws.go

Resolves https://github.com/cyberark/secretless-broker/issues/816
This PR achieve 2 goals, covered in the sections below.
The AWS service connector was altogether not working due to a naming mistake. `s/accessKeyID/accessKeyId/`.
The AWS service connector is an http proxy. It requires the client application to connect through Secretless to an HTTP endpoint. e.g. 
```
HTTP_PROXY=http://localhost:8080 aws --endpoint-url http://s3.us-east-1.amazonaws.com s3 list ...
```
This forces the client to fundamentally change how they interact with the AWS CLI (or SDK). The client must have knowledge of AWS endpoints because the client can only connect to an endpoint over HTTP when using Secretless.
Inside the AWS SDK and CLI the endpoints are determined dynamically. An improved experience with …

fix aws service connector

---

.goreleaser.yml
bin/Dockerfile.releaser
bin/build_release

An image of goreleaser build on top of dockercore/golang-cross allows us to cross-compile binaries, that use CGO, to both linux and darwin.

cross-compile linux and darwin using cross-compile goreleaser image

---

CONTRIBUTING.md
README.md
bin/juxtaposer/README.md
bin/juxtaposer/deploy/secretless.yml
demos/k8s-demo/etc/secretless.yml
demos/quick-start/docker/etc/secretless.yml
design/simpler-configuration.md
design/tls-support-plan.md
docs/_posts/2018-09-21-configuration-with-custom-resources.md
docs/tutorials/kubernetes/sec-admin.md
pkg/secretless/config/v2/config.go
pkg/secretless/config/v2/config_conversion_test.go
pkg/secretless/config/v2/config_http.go
pkg/secretless/config/v2/config_http_test.go
pkg/secretless/config/v2/config_test.go
pkg/secretless/config/v2/config_yaml.go
pkg/secretless/config/v2/doc.go
pkg/secretless/config/v2/v1_service.go
test/aws_handler/secretless.yml
test/conjur/secretless.dev.yml
test/conjur/secretless.yml
test/http_basic_auth/secretless.yml
test/plugin/secretless.dev.yml
test/plugin/secretless.yml
test/ssh_agent_handler/secretless.dev.yml
test/ssh_agent_handler/secretless.yml
test/ssh_handler/secretless.yml

1. Configuration adds support for universal `connector` spec.
1. Maintains backwards compatibility with `protocol` spec and http `authenticationStrategy`.
1. Adds unit test cases for `connector` spec.
1. References to protocol and/or authenticationStrategy in tests and sample configuration files in the main project repo are updated to use the single connector reference instead
Connected to https://github.com/cyberark/secretless-broker/issues/826

Configuration adds support for universal connector spec

---

.gitignore
Dockerfile.dev
Jenkinsfile
bin/test_unit

Reformat the default coverage output to Cobertura-compatible XML and publish
to Jenkins
Preview the code coverage report [here](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/add-jenkins-cov-report/)

Push code coverage data to Jenkins

---

internal/pkg/log/log.go
internal/pkg/log/log_test.go
pkg/secretless/log/log.go

This change adds a configurable logging object that can be used to
display log messages. Currently there are no consumers of this class but
it is intended to be used with the new plugin APIs.
Connected to #832 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/832-logging-subsystem/)

Added configurable logging subsystem

---

docs/tutorials/kubernetes/app-dev.md
docs/tutorials/kubernetes/appendix.md

Instead of using imagePullPolicy IfNotPresent use Always in the tutorial
to ensure if the person using the tutorial has an old image (eg pre-v2 config)
they download a new image before proceeding
Connected to #870

Update tutorial Secretless imagePullPolicy

---

internal/pkg/log/log_test.go

Improves the clarity of logger tests based on Oren's feedback.
Be sure to use the "Commits" tag while reviewing, which breaks down the PR and gives specific reasons for each change.

Clarify logger for oren

---

pkg/secretless/plugin/connector/connector_resources.go
pkg/secretless/plugin/connector/http/http.go
pkg/secretless/plugin/connector/tcp/tcp.go
pkg/secretless/plugin/plugin.go

Since we have a new way to interact with our plugins, the
interface is the first needed step to initiate the conversion
so this commits adds those for both http and tcp.
Connected to #852 
Diff page

Added http and tcp plugin interfaces

---

internal/pkg/plugin/available_plugins.go

This interface is used by objects that enumerate the plugins that will
be used during the runtime of the broker. Currently there are no users
of this interface.
Connected to #883 
Code diff

Added AvailablePlugins interface

---

pkg/secretless/plugin/connector/resources.go
pkg/secretless/plugin/connector/resources_test.go

We now have a way to instantiate a connector Resources interface via a
backing object. This should allow us to easily invoke the NewConnector
methods on plugins.
Connected to #840
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/840-connector-resources-int/)
N/A

Added a method to create a new connector Resources interface

---

internal/handlers/mysql/authentication_handshake.go
internal/handlers/mysql/connection.go
internal/providers/awssecrets/provider.go
internal/summon/command/command.go
test/aws_secrets_provider/aws_secrets_provider_test.go
test/conjur/conjur_provider_test.go
test/kubernetes_provider/kubernetes_provider_test.go
test/summon2/summon2_cmd_test.go
test/summon2/summon2_run_test.go
test/vault_provider/vault_provider_test.go
test/vault_provider/vault_summon_test.go

We have a standard pattern for imports that we follow that was not used
in some files. This change fixes them up to conform to the general
guidelines.
Out-of-band
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/fixup-imports/)

Fixed up imports in various files

---

demos/k8s-demo/etc/pg.yml
demos/k8s-demo/etc/quick-start-application.yml
pkg/secretless/config/v2/service.go

1. add deprecation warning for protocol key on v2 config
2. use type LoadBalancer on Services in k8s-demo to avoid NodePort conflicts

add deprecation warning for protocol key on v2 config

---

internal/plugin/available_plugins.go
internal/plugin/available_plugins_test.go
internal/plugin/external_plugins.go
internal/plugin/internal_plugins.go
internal/plugin/internal_plugins_test.go
internal/proxyservice/proxy_service.go
pkg/secretless/entrypoint/entrypoint.go
pkg/secretless/plugin/connector/http/http.go
pkg/secretless/plugin/connector/tcp/tcp.go

Adds plugin loading logic to our codebase
Connected to #878

Add AvailablePlugins module

---

internal/plugin/external_plugins.go

We assumed that the external plugin folder was always present on the
target system but that might not be the case which is a warning and not
a fatal exit condition. We now just show a warning and return no
external plugins if we are running in such an environment.
Connected to #913 
Code diff

Fixed a fatal crash when external plugin folder did not exist

---

go.sum
internal/log/log.go
internal/log/log_test.go

Adds severity levels to the logger output
Connected to #894 
Diff

894 Logging level output

---

internal/proxyservice/proxy_service.go

Old code forced listening on tcp connections so this change enables
listening to unix socket files too to recover some of the old
functionality we had previously.
Connected to #918

Add support for listening on unix socket files

---

cmd/secretless-broker/main.go

New changes made the broker not use any configuration files so the
loading failed without one explicitly specified. This change ensures
that we at least check if `secretless.yml` is available before failing.
Connected to #915 
Code diff

Use secretless.yml as configuration file by default

---

bin/run_integration
bin/test_demo
demos/k8s-demo/02_app_developer_steps
demos/k8s-demo/stop
demos/k8s-demo/test
k8s-ci/k8s_crds/deployment.yaml.sh
k8s-ci/k8s_crds/test
k8s-ci/test
test/conjur/docker-compose.yml
test/conjur/start

We've noticed two problems with the tests:
- the tests running in GKE don't always delete the namespaces that are created on exit
- the integration tests are experiencing collisions where one test removes a container running for another test
This PR updates so that all GKE namespaces will be removed on test exit, and all tests will run in their own `COMPOSE_PROJECT_NAME` so they won't have mid-air collisions
ETA: I also updated the `conjur` integration tests because they were failing on the `latest` branch - it turns out that this had already been fixed by someone (yay!) which I noticed when I cherry-picked my changes from `test-branch` to here, but I left my changes bc I think they further simplify things
You can see these changes passing on top of the `latest` branch here: …

Update tests to do a better job of cleaning up after exit

---

internal/proxyservice/http/aws/plugin.go
internal/proxyservice/http/basicauth/plugin.go
internal/proxyservice/http/proxy_service.go
internal/proxyservice/proxy_service.go
internal/proxyservice/tcp/mysql/plugin.go
internal/proxyservice/tcp/pg/connector.go
internal/proxyservice/tcp/pg/plugin.go
internal/proxyservice/tcp/proxy_service.go
pkg/secretless/plugin/connector/http/http.go
pkg/secretless/plugin/connector/tcp/tcp.go
test/plugin/example/example_plugin.go

Prior to this PR, both the tcp and http `Connector` interfaces were defined as naked functions.
While this choice was well-intentioned ("nothing is simpler than a function"), it turned out to create some awkwardness in the code itself, because we needed to refer to the "connector" (a noun) as well as _call_ it, which meant doing semantically incorrect things like `x.Connector(request, creds)` which doesn't make any literal sense.
A "connector" is still fundamentally a simple function -- that hasn't changed -- but it is now defined technically as an interface with that single function on it.  This resolves the problems mentioned above and makes talking about connectors easier and more accurate.

Connector api fix

---

README.md
demos/k8s-demo/README.md
docs/_includes/footer.html
docs/_posts/2018-12-06-meet-us-at-kubecon.md
docs/community.md

This PR updates all links in the repo / on the website to refer to the Discourse category for Secretless instead of the google group.

Update community page

---

internal/proxyservice/tcp/proxy_service_test.go

Fixes tests in `internal/proxyservice/tcp/proxy_service_test.go`
N/A

Fixed failing `proxyservice/tcp/proxy_service_test.go` tests

---

cmd/secretless-broker/main.go
internal/configurationmanagers/configfile/manager.go
internal/proxyservice/proxy_service.go
internal/proxyservice/tcp/proxy_service.go
pkg/secretless/entrypoint/entrypoint.go

New code used a bespoke (and basic) configfile loading procedure so with
these commits, we are reattaching the old configfile manager to it.
There's no new API yet, and we still need to get the CRDs configuration manager
attached but this should be a stepping stone for that.
Changes:
- Bespoke configuration loader removed
- `configfile` manager re-enabled
- Indirect result of this also enables USR1 signal reload-config trigger
- `configfile` manager modified to support this feature
- Proxy loop modified to remove existing socket files before reloading (to prevent failures from lack of cleanups)
- Main proxy loop modified to support a config channel configuration
Connected to #916 
Diff
Have you run the following manual tests to verify existing functionality continues to function as …

Reenable full configfile manager functionality

---

pkg/secretless/entrypoint/entrypoint.go
pkg/secretless/entrypoint/entrypoint_test.go

Due to ue of `os.Exit` when printing the version, our test code was
unable to print deferred output and thus the tests were failing during
conversion to xml. We now do a soft-exit so that the output can be
properly parsed as "passing"

Fixed broken entrypoint unit test

---

test/mysql_handler/start
test/mysql_handler/stop

We were creating an unstable view of the FS by adding and removing
folders for docker-compose so we are now working around that by only
doing that on MySQL handler stop action.

Fix flapping tests caused by MySQL integration tests

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
pkg/secretless/version.go

This PR bumps the Secretless version to v1.2.0.
Please review the changelog carefully, and if you have any suggestions for the prerelease notes please let me know by commenting on this PR.
Please see #901, #903, #904, and #899 (in progress) for automated unit tests we would still like to add after this effort.
We would also like to promote this release to stable, and #864 captures the work related to the performance testing we intend to perform.
Remaining docs issues include cyberark/secretless-docs#181, #863, cyberark/secretless-docs#192

Bump version to 1.2.0

---

.goreleaser.yml

At current the auto-generated homebrew tap is hardcoded to refer to the
darwin zip, but we generate both darwin and linux zip files. This PR updates
the brew def to use variables to generate the url template correctly.

Update goreleaser homebrew definition

---

bin/juxtaposer/aggregate.py
bin/juxtaposer/deploy/bootstrap.sh
bin/juxtaposer/deploy/juxtaposer_mysql.yml
bin/juxtaposer/deploy/juxtaposer_pg.yml
bin/juxtaposer/deploy/secretless.yml

- Juxtaposer default configuration have been updated
- Better error handling was added to `aggregate.py` script
Connected to #[relevant GitHub issues, eg 76]

Update juxtaposer configs

---

internal/plugin/connectors/tcp/pg/connector.go
internal/plugin/connectors/tcp/pg/protocol/auth.go
internal/plugin/connectors/tcp/pg/protocol/error.go

Instead of giving the client a useless error of the form:
```
psql: FATAL:  Expected 82 message type, got 69
```
This PR makes it so that pg errors are faithfully propagated to the client:
```
psql: FATAL:  password authentication failed for user "test"
```

improve pg error propagation

---

internal/signal/signal.go
internal/signal/signal_test.go
pkg/secretless/entrypoint/entrypoint.go

These tests ensure that we propagate signal events to all registered
handlers.
Connected to #903 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/903-signal-tests/)

Added tests to `internal/signal` module

---

Jenkinsfile
go.mod
go.sum
internal/plugin/connectors/tcp/mssql/authentication.go
internal/plugin/connectors/tcp/mssql/connection_details.go
internal/plugin/connectors/tcp/mssql/connector.go
internal/plugin/connectors/tcp/mssql/plugin.go
internal/plugin/connectors/tcp/mysql/connector.go
internal/plugin/connectors/tcp/mysql/plugin.go
internal/plugin/connectors/tcp/pg/connector.go
internal/plugin/connectors/tcp/pg/plugin.go
pkg/secretless/plugin/connector/README.md
pkg/secretless/plugin/sharedobj/internal_plugins.go
pkg/secretless/plugin/sharedobj/internal_plugins_test.go
test/mssql_connector/dev
test/mssql_connector/docker-compose.yml
test/mssql_connector/mssql_connector_test.go
test/mssql_connector/secretless.yml
test/mssql_connector/start
test/mssql_connector/stop
test/mssql_connector/test
test/mssql_connector/wait_for_mssql

This adds an end-to-end, working POC of the MSSQL connector, including a basic integration test.
Future work to make it more robust:
- Add more integration tests
- The current test suite includes:
- Application can connect to MSSQL through Secretless without creds in the request
- Application cannot connect directly to MSSQL without creds in the request
- Add UTs
- Verify the PRELOGIN response is created correctly
- Test the OK message with different TDS versions and Server versions
- Build the OK message the way we do it PG
- Check if we can extract Login Ack response details
- Run a security review of the 3rd party (https://github.com/denisenkom/go-mssqldb)
All the code changes requirements have TODOs in the code.

Add mssql connector

---

STYLE.md

The URL in the style guide pointed to a broken / incorrect location. This updated URL is taken from the 10Factor GitHub page.
None
STYLE.md
Unaffected

Broken Link: 10Factor Url corrected to reflect new location

---

internal/proxyservice/proxy_service.go
pkg/secretless/config/v1/v2_conversion.go
pkg/secretless/config/v1/v2_conversion_test.go
pkg/secretless/config/v2/config.go
pkg/secretless/config/v2/config_env.go
pkg/secretless/config/v2/config_env_test.go
pkg/secretless/config/v2/config_test.go
pkg/secretless/config/v2/service.go

History is clean-ish but could be better.
- Moves `ensureSocketIsDeleted()` out of `ProxyServices` and into `ConfigEnv`
- Add unit tests for the logic
- Move all the logic for `ConfigEnv` into its own file
- Sepatately: Changes `Service` to use a proper `NetworkAddress` type for `ListenOn`
- (related to previous point) Updates existing unit tests involving `ListenOn` as needed
- Improves formatting on some existing unit tests with long lines (since I was in the file anyway)

Move "ensureSocketIsDeleted" logic into "ConfigEnv" and unit test it.

---

internal/plugin/connectors/tcp/mysql/connection_details.go
internal/plugin/connectors/tcp/mysql/connection_details_test.go
internal/plugin/connectors/tcp/ssl/ssl.go

Old code had no way to pass this parameter into the connector so now we
support it in that capacity. This inclusion of the flag still does nto
mean that we are actively using it though.
Connected to #928 

Add support of `sslmode` parameter to the mysql plugin

---

Jenkinsfile

We've enabled Trivy (https://github.com/aquasecurity/trivy) in our Jenkins pipelines
and this commit adds it to the Secretless build to scan the Secretless image
Users aren't deploying the quick start or dev images, so those are not being scanned at this time.

Add trivy security scan to project pipeline

---

CHANGELOG.md
CONTRIBUTING.md
NOTICES.txt
assets/dependency_decisions.yml
assets/license_finder.txt
bin/check_dependencies
pkg/secretless/version.go

Bumps the version to 1.3.0 to include new automated tests and the alpha MSSQL connector, and a bug fix for MySQL to ensure the `sslmode` config has appropriate defaults.
#1003 is open for adding a README to the alpha MSSQL connector, since there is currently no documentation available for how to try it out

Bump version to 1.3.0

---

go.mod
go.sum
internal/plugin/connectors/http/generic/config_test.go

This change adds UT test cases for the generic HTTP connector's
validate method. This includes:
- Creating a common getSampleConfig() testing function for parsing
the UT sampleConfig
- Add test cases for:
* Valid username and password.
* Missing required credential.
* Credential that doesn't match corresponding validation string.
Fixes: https://github.com/cyberark/secretless-broker/issues/1025
Issue #1025 
internal/plugin/connectors/http/generic/config_test.go:Test_validate()
- [ Y ] Manually tested [Keychain provider](https://github.com/cyberark/secretless-broker/tree/master/test/manual/keychain_provider)
- [ N ] Manually run [Kubernetes-Conjur …

Adds UT test cases for generic connector validator

---

k8s-ci/Dockerfile
k8s-ci/k8s_crds/test

This change adds some minor improvements to logging for the Kubernetes
CRD tests, as suggested by @ismarc. Hopefully this will help diagnose
failures in secretless-server Issue #1027 "Failing CRD tests are fixed".
The change includes:
* For the HTTP Proxy test, change the `redirect` of stderr (to ${log}) to a
`concatenate` so that previous logs are not truncated... perhaps there are
previous errors to give us a clue.
* For Dockerfile builds, wgets of Kubernetes binaries are run in quiet
mode to eliminate lots of noise in the console logs.
Connected to #1027 
This change was tested by running the Kubernetes CRD test manually on
GKE with:
summon -f ./k8s-ci/secrets.yml -p conjurcli-docker ./k8s-ci/test k8s-ci/k8s_crds
Also, I'm running this on GKE in a loop to try to reproduce the …

Improved logs for k8s CRD test failure debugging

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
NOTICES.txt
assets/dependency_decisions.yml
assets/license_finder.txt
pkg/secretless/version.go

- Bumps the version
- Updates the acknowledgements file
- Updates the docs for the keychain provider integration test (which moved)

Bumps the version to 1.4.0

---

.gitmodules
CONTRIBUTING.md
Dockerfile
Dockerfile.dev
Dockerfile.test
Jenkinsfile
go.mod

- generated .gitmodules file with our fork of go-mssqldb
- Created new directory: /third_party, for appropriate submodules
- Updated documentation
- Updated top-level Dockerfiles to use third party submodules
Connected to #1038 and #975

go-mssqldb is a submodule within secretless

---

third_party/ctxtypes/mssql_types.go

These types can be used as keys for storing certain values in a context,
which can then be used to retrieve information elsewhere.
Connected to #[975]

Add ms-sql types

---

internal/providers/conjur/provider.go

Old code would allow a state of the broker where the token was unable to
be fetched and would end up in a non-recoverable state. This change
ensures that we both log the error poperly as well as exit the broker
when we cannot repeatedly reach the Conjur server.
Connected to #1035 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/1035-conjur-provider-graceful-failure/)

Broker logs+exits now when Conjur provider repeatedly fails

---

CONTRIBUTING.md

Provides additional instructions and details for committing changes
and using submodules

Update CONTRIBUTING documentation with submodule instructions

---

CONTRIBUTING.md
go.sum

We want master in secretless to point to safe submodule commits,
and that is reflected here.
Additionally, I've added a 'helpful commands' section that can be used to check the
hash of the current commit of a submodule that the parent
directory is pointing at.

Update contributing readme to consider best practices

---

internal/plugin/connectors/tcp/mssql/connector.go
test/connector/tcp/mssql/Dockerfile
test/connector/tcp/mssql/docker-compose.yml
test/connector/tcp/mssql/mssql_connector_test.go
test/connector/tcp/mssql/mssql_query.go
test/connector/tcp/mssql/start
test/connector/tcp/mssql/test
test/connector/tcp/mssql/test-local
third_party/ctxtypes/mssql_types.go

This PR makes enables client's param propagation via Secretless. This propagates the params that go-mssqldb supports via the Login packet:
+ Database
+ HostName
+ ServerName
+ AppName
+ TypeFlags
See https://github.com/cyberark/go-mssqldb/blob/master/tds.go#L988-L999.
~This PR relies on the ReadLogin method introduced over at cyberark/go-mssqldb#6. The build will fail until that dependency is merged.~

propagate client params via secretless

---

internal/plugin/connectors/http/proxy_service.go
internal/proxyservice/proxy_service.go

Old code gave no indication what was being listened on so this will help
debugging efforts.
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/add-more-proxy-logging/)

Added better logging of listener opening

---

examples/connector_templates/http/template/connector.go
examples/connector_templates/http/template/plugin.go
examples/connector_templates/tcp/template/connector.go
examples/connector_templates/tcp/template/plugin.go

Make sure all examples include passing the `connector.Resources.Config()` when
instantiating a new `Connector`
Also updates the comments to generalize, follow go lint standards, and remove
references to specific internal connectors

Update connector plugin examples

---

.codeclimate.yml
bin/juxtaposer/formatter/util/util.go
internal/plugin/connectors/http/aws/plugin.go
internal/plugin/connectors/http/generic/config.go
internal/plugin/connectors/ssh/proxy_service.go
internal/plugin/connectors/sshagent/proxy_service.go
internal/plugin/connectors/tcp/mssql/connector.go
internal/plugin/connectors/tcp/mysql/packet.go
internal/plugin/connectors/tcp/mysql/protocol/error.go
internal/plugin/connectors/tcp/mysql/protocol/protocol.go
internal/providers/kubernetessecrets/provider.go
pkg/secretless/config/v2/config_http.go
pkg/secretless/log/mock/logger.go
pkg/secretless/plugin/sharedobj/available_plugins.go
pkg/secretless/plugin/sharedobj/mock/http_plugin.go
pkg/secretless/plugin/sharedobj/mock/plugins.go
pkg/secretless/plugin/sharedobj/mock/tcp_plugin.go
resource-definitions/crd_injector.go
third_party/ctxtypes/mssql_types.go

This PR adds `gofmt` to the CC checks that are automatically run for each PR
It also fixes all current `gofmt` errors 
To see the results, view the CC build for this PR

Add gofmt to code climate checks

---

NOTICES.txt
go.mod
go.sum
internal/providers/conjur/provider.go

Blocked by  #1057 
We released a new authn-client that adds the ability to authenticate hosts from anywhere in the policy branch. This PR updates the version of the conjur-authn-k8s-client that is used in this project
Tests for this feature are already implemented in `kubernetes-conjur-demo`.
Connected to cyberark/conjur#1239

Update conjur-authn-k8s-client version

---

go.sum
test/connector/tcp/mssql/mssql-2017-cu1/dev
test/connector/tcp/mssql/mssql-2017-cu1/docker-compose.yml
test/connector/tcp/mssql/mssql-2017-cu1/secretless.yml
test/connector/tcp/mssql/mssql-2017-cu1/start
test/connector/tcp/mssql/mssql-2017-cu1/stop
test/connector/tcp/mssql/mssql-2017-cu1/test
test/connector/tcp/mssql/mssql-2017-cu1/test-local
test/connector/tcp/mssql/mssql-2017-cu1/wait_for_mssql
test/connector/tcp/mssql/mssql-2019/dev
test/connector/tcp/mssql/mssql-2019/docker-compose.yml
test/connector/tcp/mssql/mssql-2019/secretless.yml
test/connector/tcp/mssql/mssql-2019/start
test/connector/tcp/mssql/mssql-2019/stop
test/connector/tcp/mssql/mssql-2019/test
test/connector/tcp/mssql/mssql-2019/test-local
test/connector/tcp/mssql/mssql-2019/wait_for_mssql
test/connector/tcp/mssql/mssql_connector_test.go
test/connector/tcp/mssql/mssql_query.go
test/connector/tcp/mssql/start
test/connector/tcp/mssql/test
test/connector/tcp/mssql/wait_for_mssql
test/util/testutil/init.go

Adds IT tests for different versions of MSSQL servers
Adds IT tests for different versions of MSSQL servers
This test extends the MSSQL integration tests by adding test for
running the existing test suite against the following MSSQL server
versions:
- 2019-latest
- 2017-CU1-ubuntu
in addition to the `2017-latest` version that is used in the existing
test.
The integration tests for each new server version have been added in their
own subdirectory in the MSSQL test directory. This will allow for
different server versions to be incrementally added/removed over time
without affecting the default testing that uses MSSQL server version
2017-latest.
Each MSSQL server version test subdirectory has its own versions of
docker-compose.yml and secretless.yml that use different values of
host ports …

Adds IT tests for different versions of MSSQL servers

---

CONTRIBUTING.md

A small mistake was made in the instructions for adding a submodule.
In this section, we are telling the user how to change the 'pointer'
to the newest commit they made in the submodule. This command should be a
simple `git add <dir>`, the submodule directive is unnecessary.

CONTRIBUTING.md submodule instructions are accurate

---

Jenkinsfile
bin/run_gosec

For some odd reason, gosec exits early when pipefail is used.
Pipefail is now removed from the script that runs gosec, but is included
in the script that runs the docker container.

Fix security scan exiting early on master

---

test/connector/tcp/mssql/docker-compose.yml
test/connector/tcp/mssql/mssql-2017-cu1/start
test/connector/tcp/mssql/mssql-2017-cu1/test
test/connector/tcp/mssql/mssql-2019/start
test/connector/tcp/mssql/mssql-2019/test
test/connector/tcp/mssql/start
test/connector/tcp/mssql/test

- Add MSSQL_PID env var option to MSSQL server container (defaults to Developer)
- Removed need for Secretless host from test script - this makes it easier to
run the test scripts, bc you only have to supply config to the `start`
script. All it took was leaving the `test` container up in the `start`
script and verifying the `secretless` container was up in `start`, which
logically is reasonable anyway.
- Updated 2017-cu1 and 2019 tests to not send Secretless host to test script
If interested in trying this out, a reviewer can run `./bin/build` from the project root and from the [mssql dir](https://github.com/cyberark/secretless-broker/tree/test-mssql-editions/test/connector/tcp/mssql) run `./start -e Enterprise` to start the containers and `./test` to run the tests.
You can validate that …

Add option to specify MSSQL edition in tests

---

go.mod
internal/plugin/connectors/tcp/mssql/connector.go
internal/plugin/connectors/tcp/mssql/connector_test.go
internal/plugin/connectors/tcp/mssql/mock/mock.go
internal/plugin/connectors/tcp/mssql/mock/options.go
internal/plugin/connectors/tcp/mssql/production_options_test.go
internal/plugin/connectors/tcp/mssql/types/types.go

This PR is focused on improving the foundation of our current MsSQL tests, reducing code reuse and time needed to build new unit tests for the connector. It additionally includes a division between tests for our connector, and tests for our production options.
- NewSingleUseConnectorWithOptions allows custom injection of dependencies without needing to specify all of them
- ConnectorOptions struct captures all the configuration options for a SingleUseConnector
- ConnectorOption is the 'functional option' complement to ConnectorOptions
- Introduce tests that cover the 'production' options - dependencies we will use during production.
- Covers each option specified in the singleuseconnector
- Introduces mock options structure used for unit testing, including a function which returns default …

Introduce Functional Options for MsSQL Connector

---

Dockerfile.debug
test/connector/tcp/mssql/README.md
test/connector/tcp/mssql/docker-compose.yml
test/connector/tcp/mssql/remote_debug
test/connector/tcp/mssql/start

(LOW PRIORITY)
This change adds remote debug capability for the secretless broker.
WIth this change, a Delve-capable IDE such as Intellij/Goland can attach
to a running secretless broker container, allowing breakpoints to be set,
single-step debugging, etc.
The remote debug capability will be helpful for debugging integration tests.
(Unit tests, on the other hand, can already be easily debugged directly from
the source code without remotely connecting to into a container).
This change includes a new "debug" image for the secretless broker that
adds a Delve binary (to allow remote debug connections between the secretless
broker and an IDE), and compiles the secretless broker with code optimizations
disabled (for better debugging experience).
To use remote debugging on the secretless …

Adds remote debug capability for secretless broker

---

go.mod
go.sum

We need the new version to be able to authenticate hosts
that have their application identity defined in annotations

Use new version of conjur-authn-k8s-client

---

README.md

In the "currently supported services" section, add a reference to our SDK
so that it's clear it's possible (and easy!) to add support for a new service.
Connected to #1096

Add SDK to README

---

examples/connector_templates/http/template/README.md
examples/connector_templates/tcp/template/README.md

This PR adds README files to the connector templates so that when someone copies them to create a new connector, they can also write some initial bare-bones documentation on what the connector includes.
Connected to #1020

Add READMEs to the connector templates

---

go.sum
internal/plugin/connectors/tcp/mssql/connector_test.go
internal/plugin/connectors/tcp/mssql/mock/options.go
internal/plugin/connectors/tcp/mssql/production_options_test.go

- MSSQLConnectorCtor struct represents MSSQLConnectorCtor options
- Default constructor for an MSSQLConnectorCtor
- Wrapper function for constructing a Connector and its default methods, which can both be customized as needed

Reduce indirection of MsSQL Unit Test Framework

---

internal/plugin/connectors/tcp/mssql/connector.go
internal/plugin/connectors/tcp/mssql/connector_test.go
internal/plugin/connectors/tcp/mssql/mock/mock.go
internal/plugin/connectors/tcp/mssql/mock/options.go
internal/plugin/connectors/tcp/mssql/production_options_test.go
internal/plugin/connectors/tcp/mssql/types/types.go
test/connector/tcp/mssql/mssql_connector_test.go

This change removes any handling and translation of login responses
from the server in the secretless broker. Instead, secretless will
now "call it a day" after sending a translated version of the client's
login request to the MSSQL server. Login responses from the server
will now be passed transparently (from the perspective of secretless)
from the server to the client.
There is one integration test that is dependent on PR #1111. This
test case is commented out until that PR has been merged.
Fixes Issue #1106.

Secretless faithfully propagates MSSQL Login Response from server

---

pkg/secretless/log/mock/logger.go
pkg/secretless/plugin/sharedobj/available_plugins.go
pkg/secretless/plugin/sharedobj/available_plugins_test.go
pkg/secretless/plugin/sharedobj/external_plugins.go
pkg/secretless/plugin/sharedobj/external_plugins_test.go
pkg/secretless/plugin/sharedobj/mock/plugins.go

Currently, an external http or tcp connector plugin is allowed to replace an
internal connector plugin that has the same plugin ID.
This change removes this capability, and forces all external plugins to
use plugin IDs that are unique among all other plugin IDs.
If there is a plugin ID conflict between an external plugin and any other
plugin, then a panic occurs.
Note that there is no need to check for duplicate plugin IDs among `internal`
plugins at run time because these plugins are
hardcoded,  so that the only way that duplicate plugin IDs could occur is if the
same ID  was used twice erroneously.
The checks for uniqueness of external plugin IDs is done in 2 places:
- Right after the external plugin file content is read in and parsed. Here, each external plugin ID is compared against …

Remove the ability to override an internal plugin with external one

---

CHANGELOG.md
NOTICES.txt
assets/license_finder.txt
internal/plugin/connectors/tcp/mssql/README.md
pkg/secretless/version.go

- Bumps the version to 1.5.0
- Updates the NOTICES
- Removes the **alpha** from the MSSQL README

Bump version 1.5.0

---

docs/_data/navigation.yml
docs/_posts/adding-new-handlers.md
docs/docs/overview/how_it_works.md
docs/docs/overview/key_terms.md
docs/docs/reference.md
docs/tutorials/kubernetes/app-dev.md

In a recent update to the documentation, some of the links were changed. In light of this, several
of the pages on secretless.io needed to be updated with the new links. This PR makes those changes.

Fix broken documentation links

---

test/connector/tcp/mssql/Dockerfile
test/connector/tcp/mssql/mssql_connector_test.go
test/connector/tcp/mssql/mssql_query.go
test/util/jdbc/README.md

- Introduced custom, lightweight, jar file for testing JDBC against our various connectors
- Added table names to query structure, required for jdbc
- Created integration test for jdbc integration tests following existing pattern

Introduce JDBC Tests for MSSQL

---

test/connector/tcp/pg/Dockerfile.dev
test/connector/tcp/pg/pkg/run_test_case.go
test/connector/tcp/pg/tests/essentials_test.go
test/connector/tcp/pg/tests/init_test.go
test/connector/tcp/pg/tests/ssl_test.go

Utilizes the new JDBC Jar to test queries with postgres
- Runs several connection tests over TCP
- Created a new TestRunner that conforms to JDBC requirements

Add JDBC Integration tests for Postgres

---

bin/juxtaposer/util/signal_listener.go

This change adds the SIGPIPE signal to the list of signals that
are handled by the Secretless Juxtaposer test. The intent of the
Juxtaposer signal handler is to catch otherwise fatal signals
so that the Juxtaposer container can stay resident and running
even when fatal errors occur so that logs can be examined.
The SIGPIPE signal is being added to the list of signals being
handled because the following fatal error was observed in a
Juxatposer run after the Secretless sidecar container crashed
(because of authen issues with the Conjur follower). The error
captured was for a socket read, but the subsequent exit/crash
for the Juxtaposer could have happened on a socket write:
```
$ kubectl logs -n dane-secretless-xa juxtaposer-pg-687d4675dc-mld84 juxtaposer-pg
2020/02/04 23:18:35 Juxtaposer …
```

Adds SIGPIPE to signals handled by Secretless Juxtaposer

---

bin/juxtaposer/README.md
bin/juxtaposer/deploy/deploy_app
bin/juxtaposer/deploy/juxtaposer_deployment_template.yml
bin/juxtaposer/deploy/juxtaposer_mssql.yml
bin/juxtaposer/deploy/secretless.yml
bin/juxtaposer/go.mod
bin/juxtaposer/go.sum
bin/juxtaposer/juxtaposer.yml
bin/juxtaposer/tester/db/db.go
bin/juxtaposer/tester/db/mssql/mssql.go
bin/juxtaposer/tester/db/mysql/mysql.go
bin/juxtaposer/tester/db/postgres/postgres.go

NOTE FOR REVIEWERS: The changes proposed are based on PR #1119, which hasn't been merged yet.
To review the changes being proposed here, look at the last commit:
https://github.com/cyberark/secretless-broker/pull/1135/commits/1eade0c534a88ad82494c46ee4d7dd3417c42371
This request is a followup to PR #1119 and Issue #1129, which adds an MSSQL backend tester
to the Juxtaposer test.
While running Juxtaposer with MSSQL on OpenShift, the following error was encountered:
```
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv mssql_secretless_tcp vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
2020/02/07 17:30:09 Calling Connect from ensureWantedDbDataState, debug=true
2020/02/07 17:30:09 Connect called with debug: true
2020/02/07 17:30:09 Connection string: sqlserver://:@127.0.0.1:11433?app+name=Juxtaposer
2020/02/07 …
```

Adds database name to Juxtaposer mssql queries

---

CHANGELOG.md
Jenkinsfile
bin/parse-changelog
bin/prefill_changelog

1. Update CHANGELOG to pass validation
2. Update bin/prefill_changelog to generate valid CHANGELOG
3. Add pipeline step to validate changelog

Add pipeline step to validate changelog

---

CHANGELOG.md
internal/log/log.go
internal/log/log_test.go
internal/plugin/connectors/http/aws/connector.go
internal/plugin/connectors/http/proxy_service.go
internal/plugin/connectors/ssh/proxy_service.go
internal/plugin/connectors/sshagent/proxy_service.go
internal/plugin/connectors/tcp/mysql/connector.go
internal/plugin/connectors/tcp/proxy_service.go
internal/proxyservice/proxy_service.go
pkg/secretless/entrypoint/entrypoint.go
pkg/secretless/plugin/sharedobj/external_plugins.go

This PR increases logging by including `Info` messages in the default logging output.
Some message levels were adjusted to accommodate the change while retaining the expected
UX.
Parent: #1127 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/increase-default-logging-level/)

Increase default logging level

---

Dockerfile
bin/build
bin/publish

- Added an additional stage for building an openshift container
compliant image for secretless while making use of the build stage
- Added a stage to publishing for tagging and submitting the latest
version of the redhat compliant image
- Updated our build script to use stage targets, and since both
stages require different parameters, there would be a failure if
these target parameters would be left out, rather than overriding
an image with a different name

Add openshift registry support for secretless-broker

---

CHANGELOG.md
pkg/secretless/version.go

Bump version to 1.5.1

---

test/connector/http/conjur/docker-compose.yml

This is a new thing in `postgres:9.4` to allow all connections allow all connections without a password.

fix:conjur: set POSTGRES_HOST_AUTH_METHOD=trust 

---

NOTICES.txt
assets/license_finder.txt
go.mod
go.sum

Bumps the version of conjur-authn-k8s-client to v0.16.1
Partially resolves cyberark/conjur-authn-k8s-client#70

Bump authn-k8s client to v0.16.1

---

Jenkinsfile
bin/publish
secrets.yml

Logs into RH container registry before pushing.
Connected to https://github.com/cyberark/secretless-broker/issues/1145

Log into RH container registry before pushing

---

CHANGELOG.md
pkg/secretless/version.go

Bump version to v1.5.2

---

Jenkinsfile

Updates the Jenkinsfile to specify the `production` environment when invoking `bin/publish` using Summon

Add production env to Summon publish step

---

docs/index.md

This ensures people know we support additional services beyond the
three that are clearly shown in the quick start.
Updated quick start on main page at secretless.io:

Add link to service connector page on quick start

---

internal/plugin/connectors/http/generic/README.md

The generic HTTP connector README has some sample configs for HTTP
connectors that don't work because they use the v1 config `match` syntax
instead of the v2 config `authenticateURLsMatching` syntax
See the original v2 config design document for more info:
https://github.com/cyberark/secretless-broker/blob/master/design/simpler-configuration.md

Update README to use authenticateURLsMatching

---

README.md

Updates the README Quick Start instructions to pull the `secretless-broker-quickstart` image from Dockerhub instead of building it locally.

Update Quick Start in README

---

Jenkinsfile

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Adds scanning for the secretless-broker-quickstart and secretless-broker-redhat containers that are built as part of the pipeline.
N/A

Turning on trivy scanning for other containers built in pipeline

---

internal/plugin/connectors/tcp/mssql/connection_details.go
internal/plugin/connectors/tcp/mssql/connection_details_test.go
internal/plugin/connectors/tcp/mssql/connector.go
test/connector/tcp/mssql/mssql-2017-cu1/secretless.yml
test/connector/tcp/mssql/mssql-2019/secretless.yml
test/connector/tcp/mssql/mssql_connector_test.go
test/connector/tcp/mssql/secretless.yml

Adds sslmode as a param for user configuration and injecting it
into the DSN
Connected to #1163
internal/plugin/connectors/tcp/mssql/connector.go#dataSourceName

(#1163) Initial support for sslmode 

---

internal/plugin/connectors/tcp/pg/backend.go
internal/plugin/connectors/tcp/pg/startup.go

Some of the messages were using the non-formatted output with a
formatting string which was creating pretty unreadable logging output so
these have been fixed now.
N/A
N/A
N/A

Fixed garbled logging messages in PG connector

---

go.sum
internal/plugin/connectors/tcp/mssql/connection_details.go
internal/plugin/connectors/tcp/mssql/connection_details_test.go
internal/plugin/connectors/tcp/mssql/connector.go

sslmodes require and verify-ca dictate that TLS must
be used between secretless and the target mssql
service.
- Added support for verify-ca and building
the associated DSN
- Added support for require and building the
associated DSN
- created a map of sslmodes and their associated
params for building DSNs easily and consistently
- Modified and added tests, as needed, for the
changes and additions to connection_details.go
Todo: Add more thorough testing to verify 
parameter propagation per story #1193

1165 - MSSQL support exists for sslmodes verify-ca & require

---

internal/plugin/connectors/tcp/proxy_service.go
internal/plugin/connectors/tcp/proxy_service_test.go

In addition to a defer statement, called if we return
an error or panic after retreiving credentials, we
also call the zeroizing function immediately after
the connection is made and the credentials are no
longer needed.

1188 - Zeroize credentials immediately after connecting

---

internal/plugin/connectors/tcp/mssql/connection_details.go
internal/plugin/connectors/tcp/mssql/connection_details_test.go

Closes https://github.com/cyberark/secretless-broker/issues/1165
Closes https://github.com/cyberark/secretless-broker/issues/1199
mssql driver only supported full verification out of the box, which corresponds to sslmode=verify-full.
1. sslmode=verify-full has been added, with addition parameter sslhost that overrides the host used for verification.
2. sslmode=verify-ca has been fixed. custom verification logic has been added to ignore hostname verification.
Checklist before merge:

Update mssql driver to support verify-ca and verify-full

---

Jenkinsfile

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Adds trivy scanning for fixable issues and sets the build failures on trivy issues to only occur if a fix is available.

Builds fail only on fixable trivy issues

---

pkg/secretless/version_test.go

assert.NotNil always returns true for values that can't be nil e.g. string values. Assert.NotEmpty is more comprehensive and caters to empty strings, slice and nil values.

fix(version_test.go): Use assert.NotEmpty instead of assert.NotNil for strings

---

bin/juxtaposer/tester/db/mssql/mssql.go

Removes statement that disallows sslmodes

Allow sslmodes in mssql juxtaposer driver

---

CHANGELOG.md
internal/plugin/connectors/tcp/mssql/connection_details.go
internal/plugin/connectors/tcp/mssql/connection_details_test.go

By passing a variable into the credentials map,
we open ourselves up to an infinite loop. The variable
will be zeroed at the end of the usage for the
credentials map, which will break functionality.

Fix incorrect variable usage in MsSQL Connector

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
pkg/secretless/version.go

Bumps the project version to 1.6.0 in preparation for a new Secretless pre-release.
n/a

Bump version to 1.6.0

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/elasticsearch_secretless.yml
examples/generic_connector_configs/github_secretless.yml

- secretless yml configuration for use with elasticsearch api
- Supports both access token and api key based accesses

1212 - Generic HTTP Config Example for Elasticsearch

---

Jenkinsfile
bin/publish
bin/publish_internal

Non-internal images are published on tag-triggered builds
The Jenkinsfile is the entrypoint to the change. The publishing steps have been split in 2. 
1. An internal publish which happens only on master.
2. A non-internal publish which happens only on tags.
~~**TODO** The non-internal publish happens to also publish latest. This isn't great because if there's a retagging then latest will represent some older version.~~
~~**TODO** Should we use the TAG_NAME env var from Jenkins or should we use the VERSION in the Go file. Most of the time they should be the same. What do we do when they're not!?~~
- _Are there relevant screenshots you can add to the PR …

Secretless publishes images on tag-triggered builds

---

bin/parse-changelog

parse-a-changelog has its own Docker image. We need not manually install the `gem`.

Use parse-a-changelog image

---

Jenkinsfile

This seems to be a Jenkins specific issue. Specifying `--provider summon-conjur` on `summon` results in `stat /usr/local/lib/summon/summon-conjur: no such file or directory`.

fix: Do not specify summon provider on draft release

---

.gitleaks.toml

Adds gitleaks exception to a PG
docker-compose file that uses a dummy
password

Add PG int test exception to gitleaks

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/oauth2_secretless.yml

- Added a generic OAuth2 HTTP Connector for Secreless Broker
Connected to #328

Added a generic oauth2 http connector

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/splunk_secretless.yml

Connected to #1172
To test this out:
- I ran Splunk locally:
```
docker run \
-d \
-p 8000:8000 \
-p 8089:8089 \
-e "SPLUNK_START_ARGS=--accept-license" \
-e "SPLUNK_PASSWORD=specialpass" \
--name splunk \
splunk/splunk:latest
```
- I followed the instructions [here](https://docs.splunk.com/Documentation/Splunk/8.0.2/Security/EnableTokenAuth) for enabling and configuring a token using the Splunk UI at localhost:8000
- I added the token to my OSX keychain
- I verified API access by running the following command and getting a result:
```
summon -p keyring.py \
--yaml 'TOKEN: !var splunk/temp-token' \
bash -c 'curl -H "Authorization: Bearer $TOKEN" -X GET -i -k https://localhost:8089/services/apps/local'
```
- I ran Secretless locally by running `./bin/build_darwin` and then
``` …
```

Adds Splunk example generic HTTP config

---

examples/generic_connector_configs/README.md

Typo.  It said Slack instead of Splunk, I fixed it.

README Typo, said Slack instead of Splunk

---

CHANGELOG.md
Dockerfile
Dockerfile.debug

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
- Changes the base Alpine container to 3.12 to preserve ongoing trivy scanning

Bumping base Alpine container

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/stripe_secretless.yml

- Added a generic HTTP config for the Stripe API
Connected to #1267

Added a generic HTTP config for the Stripe API

---

CHANGELOG.md
internal/plugin/connectors/http/generic/README.md
internal/plugin/connectors/http/generic/config.go
internal/plugin/connectors/http/generic/config_test.go
internal/plugin/connectors/http/generic/connector.go
internal/plugin/connectors/http/generic/external_api.go
internal/plugin/connectors/http/proxy_service.go

This PR provides support for `query params` in the config for the generic HTTP connector. This will allow the building of a query string, with any necessary credentials injected into it.
- modified 'renderHeader' function to allow rendering of multiple input fields of the same type
- Moved the validation and saving of template strings to its own function to reduce code reuse
- Added support for passing query parameters through a secretless configuration file, and appending them to the url in the http request
To manually test this, add the `queryParam` section to the `config` subsection of a `secretless.yml` file. Add a dummy key and value (ex. foo: "bar"), and then use secretless as a proxy for an http request. The key and value should be appended to your request, and your response will …

HTTP Generic Connector supports URL parameter injection

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/twitter_secretless.yml

- Added a generic connector for Twitter's API for both OAuth 1 and 2
Connected to #1264

Added generic connector for Twitter API

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/instagram_secretless.yml

This PR adds a generic connector for the Facebook API, with an example for demoing with Instagram API. All of the API's authenticate in the same way, but the set up of the demo app sides are different. I focused on an example with Instagram, and mentioned that the rest of Facebook's tutorials could be used instead.
Connected to #https://github.com/cyberark/secretless-broker/issues/1265

Add Facebook API example connector

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/twilio_secretless.yml

- Added a generic HTTP configuration for the Twilio API
Connected to #1268

Added a generic HTTP config for the Twilio API

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/papertrail_secretless.yml

Adds a new generic HTTP connector for Papertrail
Connected to #https://github.com/cyberark/secretless-broker/issues/1276
- [ x ] This PR does not include user-facing changes and doesn't require a CHANGELOG update
- [ x ] The changes in this PR do not require tests
- [ x ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs
~~#### (For releases only) Manual tests~~

Add Generic HTTP Config for Papertrail

---

examples/generic_connector_configs/README.md
examples/generic_connector_configs/sentry_secretless.yml

- Added a generic HTTP connector config for the Sentry API
Connected to #1273

Added a generic HTTP connector config for the Sentry API

---

test/connector/ssh_agent/Dockerfile.ssh_host

This was due to phusion/baseimage changing their tags to support
multiple build architectures which broke our integration tests. We now
properly select master-amd64 tag for this.
Fixes #1322

Fix issues with ssh_agent tests breaking the build

---

.gitleaks.toml

This updates `.gitleaks.toml` to support the new config changes in gitleaks v4.  It is done in a backwards compatible way with v3 and v2 until everyone has upgraded to v4.  This will require whitelisted values or files to be update in two locations, but is the only way to support both versions.

Update gitleaks.toml to support gitleaks 4

---

CHANGELOG.md
examples/generic_connector_configs/twitter_secretless.yml
internal/plugin/connectors/http/generic/README.md
internal/plugin/connectors/http/generic/config.go
internal/plugin/connectors/http/generic/connector.go
internal/plugin/connectors/http/generic/external_api.go
internal/plugin/connectors/http/generic/oauth/v1/protocol.go
internal/plugin/connectors/http/generic/oauth/v1/protocol_test.go

- Added OAuth1 functionaly to the generic HTTP connector
Connected to #1297

Added OAuth1 functionality to the generic HTTP connector

---

.gitignore
Jenkinsfile

Update GoSec to run only on branch builds
It errors if it runs on a tag build, because it's set up to only run on branches.
n/a

Update GoSec to run only on branch builds

---

CHANGELOG.md
internal/providers/vault/README.md
internal/providers/vault/provider.go
test/providers/vault/start
test/providers/vault/vault_provider_test.go
test/providers/vault/vault_summon_test.go

Signed-off-by: Meijer <michaelmeijer@outlook.com>
- Support secrets of Vault's KV v2 backend which is incompatible with the current implementation in secretless-broker.
- New behavior is implemented with backwards compatability to current (old) behavior.
Connected to #1331

Contrib: Support Vault backend KVv2. Connected to #1331.

---

README.md

This link was broken. This change points it to the right header within
the README
N/A

Fix demo header link in README

---

CHANGELOG.md
go.mod
go.sum

This version introduces some changes that we can benefit from, especially these:
- Errors in the certificate injection process on login are now printed to the client logs.
[cyberark/conjur-authn-k8s-client#/170](https://github.com/cyberark/conjur-authn-k8s-client/issues/170)
- When authentication fails, the exponential backoff retry is correctly reset so
that it will continue to attempt to authenticate until backoff is exhausted.
[cyberark/conjur-authn-k8s-client#158](https://github.com/cyberark/conjur-authn-k8s-client/issues/158)
- Wait slightly for the client certificate file to exist after login before
raising an error.
[cyberark/conjur-authn-k8s-client#119](https://github.com/cyberark/conjur-authn-k8s-client/issues/119)

Consume version 0.19.0 of conjur-authn-k8s-client

---

bin/run_integration
go.mod
test/connector/http/basicauth/test

Our generic and basicauth tests currently exit after the
first failure. Adjustments have been made to prevent
this, so tests display all failures before exiting.
Resolves #1046

1046 - Tests don't exit on failure

---

CHANGELOG.md
NOTICES.txt
pkg/secretless/version.go

This commit increases the version to v1.7.1 in preparation to package
all the changes since v1.7.0 release.
N/A

Bumped version to v1.7.1

---

Dockerfile

Added `openssl` to the `apk` add and update command
in the secretless-image
-

Bump openssl version in images

---

CHANGELOG.md

The changelog is updated to indicate support added for OCP 4.3, 4.5 and dropped for OCP 3.9, 3.10.
Resolves conjurdemos/kubernetes-conjur-demo#122

Added entries for OCP support

---

.goreleaser.yml

Support for brews.github was removed in v0.152.0: https://goreleaser.com/deprecations/#brewsgithub
- _Are there relevant screenshots you can add to the PR description?_
Resolves #[relevant GitHub issues, eg 76]

Update goreleaser brews.github to brews.tap

---

Jenkinsfile

Goreleaser step now uses a pristine checkout for creating a release. See this passing tag build https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secretless-broker/detail/v1.7.2/2/pipeline/28.
NOTE: an alternative approach might have been to use `.gitingore` but it seems a lot more brittle than what this PR introducees.
- _Are there relevant screenshots you can add to the PR description?_
Resolves #1341

Use pristine checkout for creating a draft release

---

CHANGELOG.md
internal/plugin/connectors/http/aws/aws.go
internal/plugin/connectors/http/aws/connector.go

_What's changed? Why were these changes made?_
There were 2 bugs.
1. We modified only req.URL{Scheme, Host} with the new endpoint, we missed req.Host.
2. We were modifying the endpoint after signing the request.
2 did not show up until 1 was resolved. This is likely because the request signing doesn't
take req.URL{Scheme, Host} into account.
_How should the reviewer approach this PR, especially if manual tests are required?_
N/A
_Are there relevant screenshots you can add to the PR description?_
N/A.
Resolves #1369

Fix aws connector automatic endpoint discovery

---

go.mod
go.sum
internal/plugin/v1/testutils/testutils.go
test/providers/keychain/keychain_provider_test.go

- Fixed an erraneous assertion in our keychain tests
- replaced calls to `string()` with `strconv.ItoA`, which is the safe way to convert
an int to a string
Resolves -

Fix Keychain tests

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
go.mod
go.sum
test/providers/keychain/README.md
test/providers/keychain/cleanup_main.go
test/providers/keychain/keychain_provider_test.go
test/providers/keychain/load_test_env_vars
test/providers/keychain/shared.go
test/providers/keychain/start
test/providers/keychain/stop
test/providers/keychain/test

This PR removes the need to manually test the OSX keychain provider. This is done by refactoring the tests and running them on every commit via Github Actions.
The PR also removes the manual test for the OSX keychain provider from the PR template.
Check the Github Action runs to ensure all is well.
The Github Actions pipeline is in `.github/workflows/ci.yml`.
Most everything else is in `test/providers/keychain`. This PR mainly removes the previous tests which relied on using the `security` util on OSX to write secrets to the keychain. Instead we now use [go-keychain](https://github.com/keybase/go-keychain) in process with the tests to do this. The benefit …

Run Secretless macOS tests via Github Actions

---

CHANGELOG.md
internal/plugin/connectors/tcp/pg/connector.go
internal/plugin/connectors/tcp/pg/startup.go
test/connector/tcp/pg/tests/essentials_test.go
test/connector/tcp/pg/tests/sslmode_test.go
test/util/testutil/run_test_case.go

- Improved connection handling in PostgreSQL for SSLRequest initial packet. It now correctly signalize not supported SSL and enables downgrade to unencrypted transport. https://www.postgresql.org/docs/current/protocol-flow.html 
-  Easy testable by `psql` command with pgsqlmode changes:
- `PGSSLMODE=prefer` - didn't work in a current version
- `PGSSLMODE=disable`- worked well and is still working
- `PGSSLMODE=require` - bad signaling in the current version - now correctly prints that server doesn't support SSL instead of connection error
#1377

PostgreSQL connector supports SSL Mode = prefer from client

---

go.sum
internal/plugin/connectors/tcp/pg/backend.go
internal/plugin/connectors/tcp/pg/protocol/startup.go
internal/plugin/connectors/tcp/pg/startup.go
internal/plugin/connectors/tcp/pg/startup_test.go

Add unit tests for postgres connector handling startup messages
The test cases might look a bit scary but they're hyper specific and only deal with a single request-response message types. These are:
1. Startup message for Postgres (from the client) which contains a "version" at the start (tells us to use TLS or not), followed by options (e.g. username, database etc.).
2. Response to the client. For the tests we actually only care about the first byte which tells us if it's an error or not.
There are 3 tests
1. Corresponds to `sslmode=disable`. The client doesn't request TLS.
2. Corresponds to `sslmode=prefer`. The client requests TLS, Secretless says TLS not supported, The client sends the startup message against with no TLS request
3. Corresponds to `sslmode=INSIST!`. This one is made …

Add unit tests for postgres connector startup message logic

---

Jenkinsfile

The build would occasionally fail since multiple junit collections were being carried out as part of this arrangement of stages. Collecting at the end prevents any contention
N/A

Fix: Junit collects after all integration tests are done

---

test/connector/http/basicauth/test

Due to a recent issue with docker-compose, we need to manually check the logs rather
than asserting on the output of the original `docker-compose run` command.
Resolves -

Fix basicauth tests

---

docs/Gemfile.lock
go.mod
go.sum

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
- Updates rexml in the docs/Gemfile.lock to 3.2.5 from 3.2.4 to address CVE-2021-28965
- Updates go `text` package to 0.3.3 to address CVE-2020-14040
Dependabot alert

Update dependencies to address CVEs

---

test/connector/tcp/mssql/Dockerfile

- Changed MSSQL repo from Ubuntu 16.04 to Debian 10 (Buster), which is more appropriate for the Buster container in which the integration test is run.
- Added curl flags to retry the repo list download on error - a maximum of 5 times, 10 second timeout.
- HTTP error code will now propagate up to curl return code so CI will stop on error
N/A

Change MSSQL repo from Ubuntu to Debian and retry on repo list download failure

---

CHANGELOG.md
Dockerfile

The `rhel7/rhel` base image we've been using has a [CVE](https://access.redhat.com/security/cve/cve-2021-27219) and no updated image in sight. In this change, we move to using the `ubi8/ubi` base image for Secretless, hopefully with better results.
n/a

Update RH base image to UBI

---

CHANGELOG.md
Dockerfile
Dockerfile.debug
bin/run_gosec

Change the base Alpine container to 3.14 to preserve ongoing trivy scanning
Resolves -
- [] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs

Change the base Alpine container to 3.14 to preserve ongoing trivy scanning

---

bin/publish

Fixes `latest` tags not being pushed to DockerHub
Resolves N/A

Fix bug in check latest tag

---

bin/build_release

* The **Build Release Artifacts** step on `main` is failing in Jenkins. The current build process pulls a GoReleaser image of unknown origins from the private registry and builds with `go1.13` which fails on this repo which requires `go>=1.16`
* `bin/build_release` is modified to use a public GoReleaser docker image containing the necessary CGO-enabled cross-compilation tools. This image is recommended by the official GoReleaser docs: https://goreleaser.com/cookbooks/cgo-and-crosscompiling/
* Also now ensures the Go compiler version used matches the `GoVersion` in `go.mod`
* Build succeeds locally using the `--snapshot` flag. It *should* succeed after merge to `main`
Resolves N/A

Fix `build_release`

---

test/connector/http/conjur/start

The secretless-broker tests recently became flakey due to the Conjur wait time
not being long enough. I've doubled it and it seems to work.

Extend wait time in Conjur CI test

---

internal/configurationmanagers/kubernetes/crd/crd_injector.go
k8s-ci/k8s_crds/deployment.yaml.sh
resource-definitions/README.md
resource-definitions/crd_injector.go
resource-definitions/crd_watcher.go
resource-definitions/secretless-resource-definition.yaml

One of the ways that the CyberArk Secretless Broker (SB) can be configured is by using a Kubernetes Custom Resource Definition (CRD) that is specifically created for SB Configuration. This method of configuration is documented [here](https://github.com/cyberark/secretless-broker/tree/main/resource-definitions).
Currently, our documentation suggests that users should deploy these CRDs using the `{{apiextensions.k8s.io/v1beta1}}`
Kubernetes API version. However, support for this API version has been _*fully removed*_ in Kubernetes API controllers as of Kubernetes v1.22.
This means that any customers who want to use the Secretless Broker in Kubernetes clusters that are v1.22 or newer (or, correspondingly OpenShift v4.9 or newer) must create CRDs using the `v1` API version, that is, …

Add schema for CRD

---

CHANGELOG.md
NOTICES.txt
pkg/secretless/version.go

Release Secretless Broker
- Bump Secretless Broker to v1.7.10
- Fix Changelog entry
- Update Notices given updated `go.mod`
N/A
changes, or

Bump version to 1.7.10

---

Jenkinsfile

This is a temporary change to enable v1.7.10 release.
Jenkins build on `main` are failing due to Codertura line coverage reporting,
which is preventing a new release. This PR intends to temporarily lower the
minimum line coverage and disable the minimum coverage "ratchet" mechanism.
- Disabled `autoUpdateStability` and `autoUpdateHealth`
- Increased minimum coverage thresholds from 30% to 50%
- To ensure this is working as expected, I made a commit that removed tests, bringing the coverage figure _under_ the previous commit, but still _above_ the minimum 50% threshold. The resulting [Jenkins build](https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secretless-broker/detail/temp-lower-codecov-floor/2/pipeline/37/) did not report unsatisfactory code coverage.
Uses …

Disable Cobertura autoUpdateStability

---

bin/build_release

Goreleaser should build for the new Apple hardware
Updated to the standard goreleaser as it now supports the needed builds.
Needed by #1449 
CyberArk internal issue link: [insert issue ID]()
merged.*
changes, or

Updating the Goreleaser version

---

Jenkinsfile
internal/configurationmanagers/configfile/empty_test.go
internal/configurationmanagers/configfile/fs_watcher.go
internal/configurationmanagers/configfile/fs_watcher_test.go
internal/plugin/connectors/http/generic/connector_test.go
internal/plugin/connectors/http/generic/oauth/v1/protocol_test.go
internal/plugin/connectors/mock/empty_test.go
internal/plugin/connectors/tcp/mssql/mock/empty_test.go
internal/providers/env/empty_test.go
internal/providers/env/provider_test.go
pkg/k8sclient/clientset/versioned/empty_test.go
pkg/k8sclient/clientset/versioned/fake/empty_test.go
pkg/k8sclient/clientset/versioned/scheme/empty_test.go
pkg/k8sclient/clientset/versioned/typed/secretless.io/v1/empty_test.go
pkg/k8sclient/clientset/versioned/typed/secretless.io/v1/fake/empty_test.go
pkg/k8sclient/informers/externalversions/empty_test.go
pkg/k8sclient/informers/externalversions/internalinterfaces/empty_test.go
pkg/k8sclient/informers/externalversions/secretless.io/empty_test.go
pkg/k8sclient/informers/externalversions/secretless.io/v1/empty_test.go
pkg/k8sclient/listers/secretless.io/v1/empty_test.go
pkg/secretless/log/mock/empty_test.go
pkg/secretless/plugin/sharedobj/external_plugins_test.go
pkg/secretless/plugin/sharedobj/mock/empty_test.go
pkg/secretless/plugin/sharedobj/mock/invalid_plugin.go

The current code coverage is currently hovering around 65%. Try to get it above 70% and increase the minimum coverage to 70% in the Jenkinsfile.
Min. Coverage: 70%
Desired Coverage: 80%
Optimal Coverage: 90%
- Removed empty_test.go files from mock directories, so those directories are not counted towards coverage. This increase combined coverage from UT and integration tests to 68.7%.
- Added more unit tests to increase combined coverage to 70.7%.
- Modified Jenkinsfile to fail if combined coverage falls below 70%.
CyberArk internal issue link: [ONYX-14781](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14781)
changes, or

Increase Minimum Line Code Coverage Threshold

---

.github/workflows/ci.yml

Github Action "CI / Functional Tests on macOS" should pass.
- Removed command to uninstall go 1.15 as it's no longer installed as of actions/virtual-environments#5280. Instead, use actions/setup-go. 
N/A
changes, or

Fix GH Actions on macOS

---

Jenkinsfile

Fix Jenkins failing to promote releases generated by the new auto release process.
```
./bin/publish: line 130: REDHAT_API_KEY: unbound variable
```
- Added missing `-e common` flag when calling summon
N/A
changes, or

Add missing summon enviroinment for promoting release

---

bin/publish

Same as https://github.com/cyberark/conjur-authn-k8s-client/pull/479
- Added a script to the release-tools repository in https://github.com/conjurinc/release-tools/pull/38 which scans the OpenShift images using Red Hat's newly mandatory [preflight](https://github.com/redhat-openshift-ecosystem/openshift-preflight) tool.

Scan OpenShift image after pushing to Red Hat

---

CHANGELOG.md
bin/publish

Red Hat's preflight scan is now working thanks to #1470, but it's saving it to the wrong project. This fixes the project ID.
Additionally, this PR removes the empty `1.7.14` section of the CHANGELOG added in #1471 because that's meant to be added only after a release has been promoted.

Fix incorrect Red Hat cert project ID

---

.codeclimate.yml
Dockerfile.dev
NOTICES.txt
go.mod
go.sum
internal/plugin/resolver_test.go
internal/plugin/v1/provider_test.go
internal/plugin/v1/testutils/testutils.go
internal/summon/command/temp_factory_test.go
internal/util/health_test.go
pkg/secretless/config/config_test.go
pkg/secretless/plugin/sharedobj/checksum_verifier_test.go
test/connector/http/conjur/conjur_handler_test.go
test/connector/http/conjur/conjur_provider_test.go
test/connector/tcp/mysql/pkg/run_test_case.go
test/connector/tcp/mysql/tests/essentials_test.go
test/connector/tcp/mysql/tests/ssl_test.go
test/connector/tcp/pg/pkg/run_test_case.go
test/connector/tcp/pg/tests/essentials_test.go
test/connector/tcp/pg/tests/ssl_test.go
test/connector/tcp/pg/tests/sslmode_test.go
test/providers/awssecrets/aws_secrets_provider_test.go
test/providers/keychain/keychain_provider_test.go
test/providers/kubernetessecrets/kubernetes_provider_test.go
test/providers/vault/vault_provider_test.go
test/providers/vault/vault_summon_test.go
test/summon2/summon2_cmd_test.go
test/summon2/summon2_run_test.go
test/util/testutil/run_test_case.go

Rewrite test that used GoConvey to use a lightweight assertions library and native golang testing
Removed GoConvey from:
- internal/plugin/resolver_test.go
- internal/plugin/v1/testutils/testutils.go
- internal/plugin/v1/provider_test.go
- internal/util/health_test.go
- internal/summon/command/temp_factory_test.go
- pkg/secretless/config/config_test.go
- pkg/secretless/plugin/sharedobj/checksum_verifier_test.go
- test/connector/tcp/mysql/pkg/run_test_case.go
- test/connector/tcp/pg/pkg/run_test_case.go
- test/summon2/summon2_run_test.go
- test/summon2/summon2_cmd_test.go
- test/connector/http/conjur/conjur_handler_test.go
- test/connector/http/conjur/conjur_provider_test.go
- test/connector/tcp/mysql/tests/essentials_test.go
- test/connector/tcp/mysql/tests/ssl_test.go
- …

Remove GoConvey from tests

---

CHANGELOG.md
CONTRIBUTING.md
bin/Dockerfile.website
docs/Dockerfile
docs/Gemfile
docs/Gemfile.lock
test/connector/tcp/mysql/tests/essentials_test.go

Upgrade website Docker images to address CVE-2022-0778.
Upgrade website Docker images to their Ruby 3.0 counterparts.
CyberArk internal issue link: [CONJSE-1317](https://ca-il-jira.il.cyber-ark.com:8443/browse/CONJSE-1317)
merged.*
changes, or

Update website Dockerfiles for CVE-2022-0778

---

Jenkinsfile

After adding code coverage for integration tests and cleanup of false coverage when no tests - code coverage was around 65% with changes from @diverdane and @szh as reflected in Cobertura, but Code Climate still shows about 40%. We are not reporting the merged coverage data to Code Climate.
Report combined coverage of unit and integration tests to Code Climate, as we do for Cobertura. To do this, we wait to upload results to Code Climate until after we run the integration tests and combine the coverage data.
CyberArk internal issue link: [ONYX-17825](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-17825)
merged.*
changes, or

Report combined coverage results to CodeClimate

---

CHANGELOG.md
Jenkinsfile
bin/coverage
bin/test_unit

Several of our CI pipelines follow [this pattern](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/bin/test_unit#L31) where the script that runs unit tests sets +e to prevent unit test failure from stopping the script from running. I believe this was done to ensure that the junit tests would run even if the tests failed, but it's having the unfortunate side effect of showing the unit testing phase as green in Jenkins when a unit test fails, making it a bit unclear what's going on.
Break the junit logic into a separate script that can be run independently from the unit tests in a "post-always" block in the Jenkinsfile and return the error code when unit test(s) fail.
merged.*
changes, …

Fix false positive unit test stage

---

bin/publish

Fix Redhat image pushing by updating the scanning registry on PROMOTE to quay.io (formerly scan.connect.redhat.com)
Updates to `bin/publish` script
N/A
merged.*
changes, or

Publish RedHat images to new quay.io address

---

.goreleaser.yml
CHANGELOG.md
bin/build_release
go.sum

Fix failing release builds and prep for v1.7.17 release
- Use dir content type instead of empty folders. See:  https://goreleaser.com/deprecations/#nfpmsempty_folders
- Pin goreleaser-cross version to v1.19.4 to fix Darwin ARM builds
- Update changelog
merged.*
changes, or

Fix goreleaser deprecations and release v1.7.17

---

test/connector/http/conjur/docker-compose.yml
test/connector/tcp/mssql/Dockerfile
test/connector/tcp/pg/Dockerfile.dev

CI tests should pass
Updated the debian repositories and removed a 
conjur dependency from the conjur docker compose files to prevent rebuilding of Conjur for the test files.
Resolves #[relevant GitHub issue(s), e.g. 76]
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or

Fix CI failures

---

CHANGELOG.md
bin/publish

Fix tagging of Redhat images.
Currently we are only publishing the version tagged image, so `latest` is never updated when new images are pushed to the registry
merged.*
changes, or

Publish latest tag to redhat on promote

---

CHANGELOG.md
k8s-ci/k8s_crds/test

On an error with the CRD tests, the logs should be printed.
Update the CRD test script to print the logs.
Resolves #[relevant GitHub issue(s), e.g. 76]
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or

Update script to print logs on error
