docs/_config.yml
Since nothing is being published to prod, we can turn off maintenance mode for now.
=> Turn off maintenance mode

bin/publish, demos/k8s-demo/03_deploy_app.sh, demos/k8s-demo/etc/quick-start.yml
This should change our internal targets of the code to be DockerHub
instead of local and internal registries.
*DO NOT MERGE UNTIL PUBLIC RELEASE DATE*
Resolves #112
=> DO NOT MERGE UNTIL RELEASE DATE! Made the publish step publish to DockerHub

docs/_includes/side_navigation.html, docs/_layouts/docs.html, docs/_sass/_navbar.scss, docs/javascript/secretless.js
This adds a third tier toggle option to the side navbar in docs, allowing an opening and closing option
closes #277
TODO:
1. css styling (DONE)
2. move JS to separate file, and not on html file (DONE)
3. rotating arrow for docs (DONE)
=> Add a third tier toggle option to side-navbar for docs 

Jenkinsfile, internal/app/secretless/listeners/http/listener.go, internal/app/secretless/providers/keychain/osx.go, internal/pkg/plugin/resolver.go, internal/pkg/plugin/resolver_test.go
There was a couple of issues with linting of code that the checkstyle
was not catching.
=> Fixed linting errors with the codebase

internal/app/secretless/proxy.go
This should allow us to close the channel gracefully as well as make
sure that we don't get any panics.
=> WIP - Cleaned up channel closing in main roxy loop

Jenkinsfile, sidecar-injector/README.md, sidecar-injector/bin/build_sidecar_injector.sh, sidecar-injector/bin/publish, sidecar-injector/deployment/deployment.yaml, sidecar-injector/pkg/inject/common.go
resolves https://github.com/cyberark/secretless-broker/issues/336
=> push sidecar-injector image to dockerhub as part of CI/CD

docs/_sass/_defaults.scss, docs/_sass/_elements.scss, docs/_sass/_navbar.scss, docs/_sass/_variables.scss
This changes all the PX to REM units in scss to ensure code uniformity
closes #332
=> Change PX units to REM units

demos/k8s-demo/01_create_db.sh, demos/k8s-demo/02_configure_db.sh, demos/k8s-demo/03_deploy_app.sh, demos/k8s-demo/README.md, demos/k8s-demo/admin_config.sh, demos/k8s-demo/etc/pg.yml, demos/k8s-demo/etc/quick-start.yml, demos/k8s-demo/etc/secretless.yml, demos/k8s-demo/rotate_password.sh, demos/k8s-demo/utils.sh
Resolves #315
Validate by running through the demo :)
If you have minikube all set up it takes a 1 minute.
=> update k8s-demo to use kubernetes-secrets provider

demos/k8s-demo/01_create_db.sh, demos/k8s-demo/02_configure_db.sh, demos/k8s-demo/03_deploy_app.sh, demos/k8s-demo/README.md, demos/k8s-demo/etc/pg.yml, demos/k8s-demo/etc/quick-start-application-entitlements.yml, demos/k8s-demo/etc/quick-start-application.yml, demos/k8s-demo/rotate_password.sh, docs/Dockerfile, docs/docs/get_started/deploy_to_kubernetes.md, sidecar-injector/README.md
Resolves #316
also fixes inconsistencies between site and demo
=> update deploy with k8s on site to use kubernetes provider

go.mod, go.sum, internal/app/secretless/providers/conjur/provider.go, test/conjur/conjur_provider_test.go
+ conjur provider sends fully qualified ID with RetrieveSecret request
resolves https://github.com/cyberark/secretless-broker/issues/393
=> update conjur-api-go to v0.5.0

docs/_data/navigation.yml, docs/docs/reference/config-managers/configfile.md, docs/docs/reference/config-managers/k8s/crd.md, docs/docs/reference/config-managers/overview.md, pkg/secretless/plugin/v1/configuration_manager.go, pkg/secretless/plugin/v1/doc.go, resource-definitions/README.md, test/plugin/example/cmd/main.go
Resolves #385 
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/385-config-manager-docs/)
What this PR does:
Adds both code and website documentation about configuration plugins
=> Add configuration manager plugin docs

docs/docs/overview/how_it_works.md, docs/docs/reference.md, docs/docs/reference/config-managers/overview.md, docs/docs/reference/handlers/http/basic.md, docs/docs/reference/handlers/http/conjur.md, docs/docs/reference/handlers/overview.md, docs/docs/reference/listeners.md
A handful of other minor site updates recommended by the technical writer (mostly fixes for accuracy or clarity).
=> Additional site updates

docs/_includes/head.html
This PR adds Google Analytics tracking code to site.
Jenkins: https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secretless-broker/detail/add-analytics/1/pipeline
=> adding analytics tracking code

docs/_posts/2018-07-30-conversion-to-go-modules.md
Go module use syntax has changed since the blog post was written so we
needed a slight updating to reflect the changed CLI.
Resolves #431 
[Jenkins Build](https://jenkins.conjur.net/view/cyberark/job/cyberark--secretless-broker/job/431-go-mod-blog-updated/)
=> Updated the go mod blog post to use the newest go mod syntax

docs/_layouts/blog_index.html, docs/_posts/2019-09-24-announcing-secretless.md, docs/_sass/_blog.scss, docs/_sass/_elements.scss, docs/_sass/_grid.scss, docs/_sass/_media.scss, docs/blog.md
Closes #434 
- Fixed icon sizes for /community page
- Fixed content width for homepage on mobile (had a large left margin forcing content off the screen partially)
- Fixed CTA height
- Fixed cards for blog posts from going off-screen on mobile
- Added blog post announcing Secretless (updated blog nam to "Secretless Blog")
=> Mobile style updates & blog post

.gitignore, CHANGELOG.md, bin/prefill_changelog
It was pointing at the wrong release.
=> Fixed the unreleased link in CHANGELOG

docs/_posts/2019-09-20-announcing-secretless.md, docs/docs/get_started.md, docs/docs/get_started/quick_start.md, docs/index.md
**What does this PR do?**
- Updates the Announcing Secretless blog post with a few small content updates
- Changes the Quickstart language a bit so it's clear that users will go through a demo, not get Secretless up & running for their environments.
=> Blog post & Quick Start content updates

README.md, internal/app/secretless/configurationmanagers/kubernetes/crd/k8s_config.go, test/k8s_crds/deploy, test/k8s_crds/deployment.yaml, test/k8s_crds/first-v1.yaml, test/k8s_crds/first-v2.yaml, test/k8s_crds/stop_deployment
The changes here add both a test deployment and it also fixes issues
with auto-configurating in-cluster ServiceAccount.
=> Fix in-cluster CRD retrieval

docs/_layouts/blog.html, docs/_posts/2018-09-18-announcing-secretless.md
Also, unpublish announcement blog pending further review
=> Enable blogs to have published=false and not show

docs/docs/overview/security.md
Resolves #454
Text needed a bit more clarification and language restructuring on this
page so this commit fixes it.
=> Update the Security page to address comments from internal comments

internal/pkg/plugin/manager.go, pkg/secretless/plugin/v1/doc.go
Resolves #418 
- Fixes a minor typo in manager.go
- Updates the godoc overview for the plugin to render more nicely on secretless.io / godocs.org
=> Plugin documentation is updated to be easier to read

.gitlab-ci.yml
closes #363 
See https://gitlab.com/cyberark/secretless-broker/pipelines :)
=> add gitlab-ci pipeline

README.md
=> Update README.md to revise GOPATH section

bin/test_unit, go.sum, internal/app/secretless/handlers/pg/backend.go, internal/pkg/util/util.go
1. Made one of our shell scripts compliant with shellcheck
2. Created a utility function for conditional debugging, and refactored a file with a lot of repeated `if` boilerplate to use it instead.
Jenkins:
https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secretless-broker/detail/tiny-cleanup/7/pipeline
=> A bit of refactoring and cleanup 

.gitlab-ci.yml
Connected to #522
[GitLab build](https://gitlab.com/cyberark/secretless-broker/commit/9b160d12b9a6f9573a778d8e7abbce0a831f066b/pipelines?ref=fix-gitlab-build) for reference
=> Only save the latest build locally in GitLab

internal/app/secretless/providers/kubernetessecrets/client.go, internal/app/secretless/providers/kubernetessecrets/provider.go, test/kubernetes_provider/kubernetes_provider_test.go
=> fix(k8s provider): use non-empty current namespace to fetch secrets

CONTRIBUTING.md, design/tls-support-plan.md, docs/docs/reference/handlers/postgres.md
Plan for downstream TLS Support on Database Handlers
Connected to #460
=> DO NOT MERGE: plan for TLS Support for Database Handlers

docs/docs/overview/security.md
Seems like there was a spelling problem :(
=> Fixed minor typo in security.md

test/ssh_handler/test
Connected to #658 (does not resolve issue - just turns test off until it can be resolved)
=> Temporarily turn off SSH handler test

test/ssh_handler/Dockerfile.ssh_host, test/ssh_handler/start, test/ssh_handler/test
Fixes ssh handler test
Connected to #658 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/658-fix-ssh-handler-test/)
Not needed
=> Fix ssh handler test

bin/abspath, bin/build, bin/build_darwin, bin/build_release, bin/build_website, bin/check_website_links, bin/codegen, bin/cpu_profiling, bin/prefill_changelog, bin/publish, bin/publish_website, bin/test_benchmarks, bin/test_demo, demos/full-demo/build, demos/full-demo/conjur/5_run_tls_frontend, demos/full-demo/plaintext/4_run_tls_frontend, demos/quick-start/bin/test, demos/quick-start/docker/bin/entrypoint
This fixes a whole bunch of codeclimate shellcheck errors
=> Fix all non-TODO CodeClimate issues

bin/publish_website
Hotfix for broken website publishing
=> Fix broken website publishing

test/vault_provider/start
- With the 1.10 vault release, some CLI commands are updated - including mount
see the [vault changelog](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#110-march-18th-2019)
- Update the tests to use new methods to add secrets to the vault
=> Update test vault command used to add secrets

README.md, docs/docs/reference/providers/kubernetes.md
=> document k8s secrets provider

README.md
=> fix kubernetes secrets example in README

design/simpler-configuration.md
Adds a design doc for the updated configuration
=> Add design doc for simplified Secretless configuration

design/simpler-configuration.md
=> Add final improvement to proposed syntax

design/simpler-configuration.md
=> Change config syntax to reflect final public consensus

bin/view_godocs, pkg/secretless/config/v2/config.go, pkg/secretless/config/v2/config_conversion_test.go, pkg/secretless/config/v2/config_http.go, pkg/secretless/config/v2/credential.go, pkg/secretless/config/v2/doc.go, pkg/secretless/config/v2/v1_service.go
Adds a script to make viewing docs locally easy.  Improves v2 docs.
#735 
Simply run:
```
./bin/view_godocs
```
And paste into the URL that cmd outputs for you.  Find the v2 docs in the package list there.
=> Improve v2 package docs.  Add script for viewing locally.

bin/juxtaposer/README.md
Simple improvements to juxtaposer README.
View it on gh so you can see the table.
=> Add comparison md table and other minor cleanup

bin/juxtaposer/deploy/deploy_app, bin/juxtaposer/deploy/stop
=> scope juxtaposer deploy to TEST_APP_NAMESPACE_NAME

bin/juxtaposer/deploy/juxtaposer_deployment_template.yml
=> Update perf agent deployment namespace

CHANGELOG.md, internal/app/secretless/providers/conjur/provider.go
=> refactor authenticate loop

bin/juxtaposer/README.md
This change adds more information needed to run the perf agent
(juxtaposer) locally to evaluate its functionality.
Connected to #756 
README.md
N/A
=> Added info to README about how to run perf agent locally

internal/app/secretless/handlers/mysql/authentication_handshake.go, internal/app/secretless/handlers/mysql/handler.go, internal/app/secretless/handlers/mysql/protocol/error.go, internal/app/secretless/handlers/mysql/protocol/protocol.go, internal/app/secretless/handlers/pg/handler.go, internal/app/secretless/handlers/pg/protocol/error.go, internal/app/secretless/listeners/mysql/listener.go, internal/app/secretless/listeners/pg/listener.go, test/mysql_handler/test, test/mysql_handler/tests/essentials_test.go, test/util/test/backend_configuration.go, test/util/test/config_generator.go, test/util/test/types.go
Connected to https://github.com/cyberark/secretless-broker/issues/766
=> propagate mysql auth handshake errors to client

README.md, docs/_posts/2018-09-21-configuration-with-custom-resources.md, docs/_posts/adding-new-handlers.md, docs/docs/reference/handlers/http/aws.md, docs/docs/reference/handlers/http/basic.md, docs/docs/reference/handlers/http/conjur.md, docs/docs/reference/handlers/mysql.md, docs/docs/reference/handlers/overview.md, docs/docs/reference/handlers/postgres.md, docs/docs/reference/handlers/ssh.md, docs/docs/reference/handlers/ssh_agent.md, docs/docs/reference/listeners.md, docs/tutorials/kubernetes/app-dev.md, docs/tutorials/kubernetes/appendix.md, docs/tutorials/kubernetes/finish.md, docs/tutorials/kubernetes/kubernetes-tutorial-base.md, docs/tutorials/kubernetes/overview.md, docs/tutorials/kubernetes/sec-admin.md
Connected to cyberark/secretless-docs#174
=> Rename from service authenticators to service connectors

.gitignore, CONTRIBUTING.md, Jenkinsfile, bin/run_integration, bin/test_unit, demos/quick-start/test/bin/entrypoint, k8s-ci/k8s_crds/test, test/pg_handler/start, test/pg_handler/wait-for-pg
This makes all integration tests run in parallel, so they are much faster (total running on Jenkins is now about 3 minutes)
Don't think it has one.
Definitely start on the Commits tab.
All commits have been broken down into small, logically coherent pieces that can be reviewed in isolation.  This will make reviewing easy.
Not run.
#781 should probably be merged before this, though it's not required as long as both are merged relatively quickly.
=> Integration tests run in parallel

docs/_includes/quick_start.html, docs/_sass/_elements.scss, docs/index.md
- Add info about downloading docker
- Clarify that the first step both downloads and installs the image
=> Modify quick start instructions

.gitleaks.toml
Adds a gitleaks config file to the project
Includes exceptions for many test / demo / sample files
=> Added gitleaks config

README.md
This PR updates the README:
- To remove old content documenting components and refer users to the documentation website instead
- To make minor revisions to the language describing the project
- To add notes about where to find releases, and when to use which one
- To add notes about what "stability" means in the context of this project
Connected to #812
=> Update README to add information about releases

Jenkinsfile, demos/k8s-demo/01_security_admin_steps, demos/k8s-demo/02_app_developer_steps, demos/k8s-demo/README.md, demos/k8s-demo/app_constants.sh, demos/k8s-demo/etc/quick-start-application.yml, demos/k8s-demo/test, demos/k8s-demo/utils.sh, k8s-ci/k8s_crds/deployment.yaml.sh, k8s-ci/k8s_crds/stop_deployment, k8s-ci/k8s_crds/test, k8s-ci/platform_login, k8s-ci/test, k8s-ci/utils.sh
Runs k8s-demo on each Jenkins build
Connected to #542 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/542-automate-k8s-demo/)
=> 542 Automate k8s demo

k8s-ci/utils.sh, test/conjur/Dockerfile.dev, test/conjur/docker-compose.yml, test/conjur/start
=> fix failing builds on master

pkg/secretless/config/v1/config.go, pkg/secretless/config/v2/config_http.go, pkg/secretless/config/v2/v1_to_v2.go, pkg/secretless/config/v2/v1_to_v2_test.go
Adds capability to translate v1 config to v2 config
Connected to #835
=> Add capability to translate v1 config to v2 config

docs/_includes/quick_start.html
Make sure people using the demo know to send the commands from outside of the
container so that they can have the intended experience
Connected to cyberark/secretless-docs#189
=> Update quick demo to have clearer directions

internal/app/secretless/proxy_service.go
Adds ProxyService interface
Check the diff
=> add ProxyService interface

demos/k8s-demo/02_app_developer_steps, k8s-ci/k8s_crds/test
limit k8s demo wait script to avoids forever builds
=> limit k8s demo wait script

internal/log/log.go, internal/log/log_test.go, internal/profile/profile.go, internal/proxy_service.go, internal/proxyservice/proxy_service.go, internal/proxyservice/tcp/proxy_service.go, internal/signal/signal.go, pkg/secretless/config/v2/service.go, pkg/secretless/entrypoint/entrypoint.go, pkg/secretless/log/log.go, pkg/secretless/secretless.go
=> 853 proxy services

internal/proxy_service.go, internal/proxyservice/http/proxy_service.go, internal/proxyservice/proxy_service.go, internal/proxyservice/tcp/proxy_service.go
=> 848 http proxy service exists

internal/proxyservice/http/aws/aws.go, internal/proxyservice/http/basicauth/connector.go, internal/proxyservice/http/basicauth/plugin.go, internal/proxyservice/http/proxy_service.go, pkg/secretless/entrypoint/entrypoint.go, pkg/secretless/plugin/sharedobj/internal_plugins.go, test/http_basic_auth/docker-compose.yml, test/http_basic_auth/secretless.yml, test/http_basic_auth/test
Commits are clean.  Please review via Commits tab.
This PR adds back the basic auth connector.
=> 860 basic auth connector exists

internal/proxyservice/proxy_service.go
The new refactoring changed the Resolver isntance from stateful to
stateless, causing various problems with instantiating providers. The
change here returns that behavior to the previous one.
Connected to #959
=> Cache credentials resolver

pkg/secretless/plugin/connector/README.md
- Link to connector templates from plugin docs
- minor improvements
=> Link to connector templates from plugin docs

internal/profile/profile.go, internal/profile/profile_test.go, pkg/secretless/entrypoint/entrypoint.go
Refactors the profile class to have simpler usage of the API and adds tests for the class.
Connected to #901 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/901-profile-tests/)
=> 901 profile tests

internal/plugin/connectors/ssh/service_connector.go, internal/plugin/connectors/tcp/mysql/connection_details.go
Addresses three small issues found via code climate linting.
Connected to #[554]
No code was modified - only comments.
=> Fixing remaining code-climate issues

Jenkinsfile, go.mod, go.sum, internal/plugin/connectors/http/generic/config.go, internal/plugin/connectors/http/generic/config_test.go, internal/plugin/connectors/http/generic/connector.go, internal/plugin/connectors/http/generic/plugin.go, internal/plugin/connectors/ssh/service_connector.go, k8s-ci/k8s_crds/test, pkg/secretless/plugin/sharedobj/internal_plugins.go, pkg/secretless/plugin/sharedobj/internal_plugins_test.go, test/http_generic/basic_auth.htpasswd, test/http_generic/docker-compose.yml, test/http_generic/http-basic-auth.conf, test/http_generic/secretless.yml, test/http_generic/start, test/http_generic/stop, test/http_generic/test, test/mssql_connector/start, test/mssql_connector/wait_for_mssql
TBD but....
Quick explanation:
- Creates a generic http connector
- Integration test shows how to use it to recreated Basic Auth connector
- Includes unit tests, though they aren't exhaustive.
=> 999 generic http connector

internal/plugin/connectors/http/generic/README.md
This commit adds detailed docs for both end-users and developers.
=> Add REAMDE for Generic HTTP connector

docs/Dockerfile
This change addresses a version mismatch between Ruby and
jekyll-sass-converter in the docs container. With the current
implementation, when the docs container is started with:
```
cd docs
docker-compose up -d
```
then an error is reported when the container is being built:
```
ERROR:  Error installing jekyll:
There are no versions of jekyll-sass-converter (~> 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
jekyll-sass-converter requires Ruby version >= 2.4.0. The current ruby version is 2.3.7.456.
```
The fix is to upgrade the container to Ruby 2.4.0.
Fixes Issue #1028
This PR addresses a version mismatch error that is seen when the docs container is run via
`docker-compose up -d`, as described above.
Connected to #1028 …
=> Updates Ruby version in docs container

test/connector/tcp/mssql/README.md
=> Add README for the mssql connector

CONTRIBUTING.md
We want to use a specific commit for the submodule, rather than
pointing to master. This way, we can avoid breaking secretless
with any changes we haven't considered within the submodule.
N/A
N/A
=> Modify submodule reference

internal/configurationmanagers/configfile/manager.go
Old code only recorded that we hit an error but provided no clarity on
what the problem might be. This change ensures that we show the error as
well since it may contain vital info on what the problem might be.
Connected to #1062 
[Jenkins Build](https://jenkins.conjur.net/job/cyberark--secretless-broker/job/1062-better-configfile-error-logging/)
=> Add better logging to configuration file log messages

internal/plugin/connectors/tcp/mssql/connector_test.go
Connected to:
PR #1089 
Issues:
#1074 
#1075
=> 1074 & 1075 ReadLogin and WriteLogin tests

internal/plugin/connectors/tcp/mssql/connector_test.go
- WritePreloginSucceeds test
- The production version of WritePreloginWithPacketType
succeeds when all others succeed
- We receive the prelogin fields from the go-mssqldb driver
- We modify the prelogin fields before sending them to the user
- WritePreloginFails test
- Error is returned from connect
- Error is written to client buffer
- Error written to log
Connected to #1070
=> 1070 MsSQL WritePrelogin Unit Test Exists

internal/plugin/connectors/tcp/mssql/connector_test.go
Connected to #1069 
internal/plugin/connectors/tcp/mssql/connector_test.go
=> 1069 Readprelogin Failing Test Exists

internal/plugin/connectors/tcp/pg/protocol/protocol.go, internal/plugin/connectors/tcp/pg/protocol/protocol_test.go, internal/plugin/connectors/tcp/pg/protocol/startup.go
=> Postgres connector validates packet lengths

internal/plugin/connectors/tcp/mssql/connector.go, internal/plugin/connectors/tcp/mssql/production_options_test.go, test/connector/tcp/mssql/Dockerfile, test/connector/tcp/mssql/mssql_connector_test.go, test/connector/tcp/mssql/mssql_query.go, test/connector/tcp/mssql/odbc_client.py
Must first merge https://github.com/cyberark/go-mssqldb/pull/19
Resolves #1107
=> faithfully propagate loginrequest via connectInterceptor 

internal/plugin/connectors/tcp/mssql/connector.go, internal/plugin/connectors/tcp/mssql/production_options_test.go, test/connector/tcp/mssql/Dockerfile, test/connector/tcp/mssql/mssql_connector_test.go, test/connector/tcp/mssql/mssql_query.go, test/connector/tcp/mssql/odbc_client.py
Must first merge https://github.com/cyberark/go-mssqldb/pull/19
Resolves #1107
=> 1107 faithful login request

test/connector/tcp/mssql/docker-compose.yml, test/connector/tcp/mssql/mssql-2017-cu1/docker-compose.yml, test/connector/tcp/mssql/mssql-2019/docker-compose.yml, test/connector/tcp/mssql/start, test/connector/tcp/mssql/test
- Allows the creation of a docker container based on the pet store demo app
- Runs a few queries against the app to verify jdbc support in secretless
Connected to #1109
=> WIP: Add JDBC integration test support

bin/publish
Added clarification to the if statement
Connected to #[relevant GitHub issues, eg 76]
=> Added comment

pkg/secretless/config/v2/config.go, pkg/secretless/config/v2/config_yaml.go, pkg/secretless/config/v2/service.go, pkg/secretless/config/v2/service_test.go, test/util/testutil/cmd/generate_secretless_yml.go, test/util/testutil/config_generator.go, test/util/testutil/types.go
Resolves https://github.com/cyberark/secretless-broker/issues/990
=> Convert integration tests to use configs.v2

.github/ISSUE_TEMPLATE/feature_request.md
Connected to #[relevant GitHub issues, eg 76]
=> Fix feature-request template formatting

.codeclimate.yml
Introduces our standard .codeclimate.yml file, while preserving the pre-existing exceptions the secretless team had already defined.
=> Add codeclimate yml

examples/generic_connector_configs/README.md, examples/generic_connector_configs/github_secretless.yml
Create a folder for new generic HTTP examples and add one for the github API
=> Create a folder for generic HTTP connector example

internal/plugin/connectors/tcp/mssql/connection_details.go, internal/plugin/connectors/tcp/mssql/connection_details_test.go
- Parse additional ssloptions if sslmode is enabled
- Check for option existence based
on length rather than being non-nil, following
the pattern set by our other connectors
=> Add support for additional ssl options

Jenkinsfile, demos/quick-start/docker/Dockerfile
- Introduces fixes for any 'high' level trivy issues in the redhat and quickstart containers
- Lowers the trivy issue threshold to 'high'
=> WIP - 1176 - Lower trivy threshold to detect 'high' level issues

bin/juxtaposer/README.md
Added small note at the end of the juxtaposer run instructions
to specify changing the value of the ignore field as needed
=> Add note on ignoring values in juxtaposer README

.gitleaks.toml, internal/plugin/connectors/tcp/mssql/connection_details_test.go
- Introduces a test driven unit test for the
connection_details URL() function in the
MsSQL Connector
=> 1224 - Unit Test for MsSQL URL Function

bin/juxtaposer/README.md, bin/juxtaposer/deploy/bootstrap.sh, bin/juxtaposer/deploy/deploy_app, bin/juxtaposer/deploy/juxtaposer_deployment_template.yml, bin/juxtaposer/deploy/secretless.yml
- Fixed spelling occurrences of the word "secretless"
- Changed default values in the bootstrap script to
"CHANGEME"
- ToC added to README
=> Juxtaposer documentation fixes

go.mod, test/connector/tcp/mssql/README.md, test/connector/tcp/mssql/client/client.go, test/connector/tcp/mssql/client/odbc_client.py, test/connector/tcp/mssql/client/query.go, test/connector/tcp/mssql/mssql_client_request.go, test/connector/tcp/mssql/mssql_connectivity_test.go, test/connector/tcp/mssql/mssql_defaults.go, test/connector/tcp/mssql/mssql_mock_target.go, test/connector/tcp/mssql/mssql_propagate_params_test.go, test/connector/tcp/mssql/mssql_proxy_service.go, test/connector/tcp/mssql/mssql_tls_test.go
- Refactor tests into matrix/table where possible
- Refactor test client into separate client package
Connected to https://github.com/cyberark/secretless-broker/issues/1226
=> Mssql tech debt

.goreleaser.yml, Jenkinsfile, bin/Dockerfile.releaser, bin/build_release
+ Goreleaser runs in pipeline and saves artifacts in Jenkins
+ Goreleaser docker uses latest Go releaser version
The root of the changes are:
+ Jenkinsfile
+ Dockerfile.relaser
- _Are there relevant screenshots you can add to the PR description?_
Connected to #1234 and #1235
=> Goreleaser runs in pipeline and saves artifacts in Jenkins

CONTRIBUTING.md
Edits the instructions for the project submodules based on [this discourse conversation](https://discuss.cyberarkcommons.org/t/how-to-start-secretless-locally-using-provided-build-darwin-script/827)
n/a
=> Update command for fetching submodules

README.md
- Updated broken links in README.md
Connected to #1254
=> Broken readme links

CONTRIBUTING.md
- Updated broken command in #building of the contributing guide
N/A
=> Updated contributing guide to fix command in building

examples/generic_connector_configs/README.md
- Reorganized Generic HTTP Config Connector README for easier readability
Connected to #1286
=> Reorganized Generic HTTP Config Connector README for easier readability

examples/generic_connector_configs/README.md
Changes "Github" to "GitHub", "ElasticSearch" to "Elasticsearch", etc.
N/A
=> Capitalizing 3rd-party brand names and trademarks

examples/generic_connector_configs/README.md, examples/generic_connector_configs/docker_registry_secretless.yml
Adds a generic connector for connecting to a Docker Registry and updates the README with details
=> Add Docker Registry generic connector

examples/generic_connector_configs/README.md, examples/generic_connector_configs/tableau_secretless.yml
- Added a generic HTTP connector for Tableau
Connected to #1278
=> Added a generic connector for Tableau

examples/generic_connector_configs/README.md, examples/generic_connector_configs/mailchimp_secretless.yml
Add a generic connector for authenticating with the Mailchimp API
Connected to https://github.com/cyberark/secretless-broker/issues/1269
- [ x ] This PR does not include user-facing changes and doesn't require a CHANGELOG update
- [ x ] The changes in this PR do not require tests
- [ x ] Docs (e.g. `README`s) were updated in this PR
=> Add a generic connector for Mailchimp

examples/generic_connector_configs/README.md, examples/generic_connector_configs/datadog_secretless.yml
- Added a generic connector for the Datadog API
Connected to #1272
=> Added Datadog generic connector config

examples/generic_connector_configs/README.md, examples/generic_connector_configs/dropbox_secretless.yml
- Added a generic configuration for the Dropbox API
Connected to #1266
=> Added generic Dropbox config

examples/generic_connector_configs/README.md, examples/generic_connector_configs/sendgrid_secretless.yml
- Added generic connector config for SendGrid
Connected to #1270
=> Added SendGrid generic connector config

examples/generic_connector_configs/README.md, examples/generic_connector_configs/google_maps_secretless.yml, go.sum
- Added a generic connector config the the Google Maps Web Services API
Connected to #1259
=> Added a generic HTTP connector config for the Google Maps API

examples/generic_connector_configs/README.md, examples/generic_connector_configs/jfrog_artifactory_secretless.yml
- Added a generic connector config for the JFrog Artifactory Rest API
Connected to #1263
=> Added a generic config for the JFrog Artifactory REST API

examples/generic_connector_configs/README.md, examples/generic_connector_configs/loggly_secretless.yml
- Added an HTTP generic connector config for the Loggly API
Connected to #1275
=> Added a generic connector config for the Loggly API

examples/generic_connector_configs/README.md, examples/generic_connector_configs/new_relic_secretless.yml
- Added a generic connector config for the New Relic API
Connected to #1274
=> Added a generic connector config for the New Relic API

examples/generic_connector_configs/README.md, examples/generic_connector_configs/oauth1_secretless.yml
- Added an `oauth1_secretless.yml` file example, and documented that + the Twitter OAuth1 flow
Connected to #1327
=> Added a generic OAuth1 example

examples/generic_connector_configs/README.md, examples/generic_connector_configs/full_contact_secretless.yml
- Added a configuration for the Full Contact API
Connected to #1329
=> Added a configuration for the Full Contact API

examples/generic_connector_configs/README.md, examples/generic_connector_configs/service_now_secretless.yml
- Added a Service Now configuration example
Connected to #1284
=> Added a Service Now configuration example to Secretless

CONTRIBUTING.md, docs/community.md
Depends on cyberark/community#74
Connected to cyberark/community#1
=> Update the link for the contrib license guide

CHANGELOG.md
This PR adds a missing PR link to the changelog.
=> Add missing Changelog link

CHANGELOG.md, NOTICES.txt, pkg/secretless/version.go
Bumps version to v1.7.2
Resolves #1367
=> Bump version to v1.7.2

.github/workflows/ci.yml
Add tests to Github Actions CI
N/A
=> Add tests to Github Actions CI

.github/workflows/ci.yml, Dockerfile.test, Jenkinsfile, bin/test_unit
Run unit tests at the start
N/A
=> Run unit tests at the start

README.md
=> Add trademark to Secretless README

internal/providers/conjur/provider.go
Allow authn-jwt flow in conjur provider 
Resolves #[relevant GitHub issue(s), e.g. 76]
ONYX-15241
merged.*
changes, or
=> ONYX-15241: Add fixing line in conjur provider to support authn-jwt

go.mod
Unpinned internal dependencies needed for automated releases will have issues when there are indirect dependencies that are specified as `latest`.  This applies the pattern that corrects the issue and allows `go mod` to properly parse the go.mod files of dependencies
- Update to specify replace of necessary subcomponents to always use latest version
changes, or
=> Update to support latest version usage of dependencies

CHANGELOG.md, CONTRIBUTING.md, pkg/secretless/version.go
Bump version to 1.7.13 - include yaml.v3 security fixes, among others.
- Update release date for 1.7.13 in Changelog
- Add new, empty 1.7.14 Changelog section to satisfy auto-release process
- Bump version in `version.go`. This file isn't being used in the auto-release process, so I'm updating it here for consistency.
N/A
merged.*
changes, or
=> Bump version to 1.7.13

CHANGELOG.md, pkg/secretless/version.go
Prepare to promote v1.7.14
changes, or
=> Bump version to 1.7.14

CHANGELOG.md
Fix release builds in jenkins
Bump changelog version to be higher than last promotion (v1.17.16)
merged.*
changes, or
=> Bump changelog version to be higher than last promotion

bin/juxtaposer/tester/db/db.go, internal/plugin/connectors/http/generic/oauth/v1/protocol.go, internal/plugin/connectors/http/proxy_service.go, test/connector/http/generic/http_test_server.go
Address gosec warnings in pipeline
=> Fix gosec warnings
